/**
 * Lode Runner level definitions — all 150 Classic Apple II (1983) levels.
 *
 * Grid: 28 cols x 16 rows. Each character is a tile:
 *   . = empty       B = brick (diggable)     S = solid (indestructible)
 *   H = ladder      - = bar (monkey bar)     G = gold
 *   P = player      E = enemy start          T = hidden ladder (escape)
 *   X = trap brick (looks like brick but entities fall through)
 *
 * Bottom of screen acts as floor (out-of-bounds = solid).
 * Hidden ladders (T) appear when all gold is collected.
 */

export type LevelDef = string[]

// Each level is exactly 16 rows x 28 cols.

const LEVEL_1: LevelDef = [
  '..................T.........',
  '....G.............T.........',
  'BBBBBBBHBBBBBBB...T.........',
  '.......H----------T....G....',
  '.......H....BBH...BBBBBBBHBB',
  '.......H....BBH..........H..',
  '.....E.H....BBH.......GE.H..',
  'BBHBBBBB....BBBBBBBBHBBBBBBB',
  '..H.................H.......',
  '..H...........E.....H.......',
  'BBBBBBBBBHBBBBBBBBBBH.......',
  '.........H..........H.......',
  '.......G.H----------H...G...',
  '....HBBBBBB.........BBBBBBBH',
  '....H.........P..G.........H',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_2: LevelDef = [
  '...G.......................H',
  'HSSBSSH...........G........H',
  'H.....H....HBBBBBBBBBH.G...H',
  'H.G.E.H....H.........HBBBBXH',
  'HBSBSBH....H.........H.....T',
  'H.....H----H------..EH.....T',
  'H.....H....H.....HBBBSSSSSSH',
  'H.....H....H..G..H.........H',
  'H...E.H.G..HBBBBBH.........H',
  'SBBBSBBSBBSH.........HBBBHBB',
  'SBBBS......H.........H...H..',
  'SG..S......H...------H...H.G',
  'BBBBBBBBHBBBSSSS.....H..BBBB',
  '........H............H......',
  '........H...P........H......',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_3: LevelDef = [
  '...........................T',
  '----------....G............T',
  'H.G......HBBBBBBBBBBH......T',
  'BBBBBH...H..........HSSSSSSS',
  '.....H.E.H.....G....H.......',
  '.....HBBBBBBHBBBBBHBB.......',
  '..G..H......H.....H..--.....',
  'BBBBHB......H..E..H....--...',
  '....H....HBBBBBBHBB......--G',
  '....H----H......H..E.......B',
  '....H.......HBBBBBBBBBH.....',
  '....H.......HBBBBBBBBBH.....',
  'BBBHBBBBBBBBBB...G...BBBBBHB',
  'BBBHBBBBBBBBBB.HBBBH.BBBBBHB',
  '...H......P....HBBBH...G..H.',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_4: LevelDef = [
  'T...........................',
  'T-----------................',
  'H.....H.....B.G.B.....H.....',
  'H.G..HHH..G.BBBBB.G..HHH..G.',
  'H.HH..H..HH.......HH..H..HH.',
  'H.H.HHHHH.H.......H.HHHHH.H.',
  'H.H..GEG..H...H...H..GEG..H.',
  'H..HBBBBBH...HHH...HBBBBBH..',
  'H...HHHHH.HH..H..HH.HHHHH...',
  'H.........H.HHHHH.H.........',
  'H....G....H..GEG..H.....G...',
  'HBBBBBBH...HBBBBBH..HBBBBBBB',
  'H......H....HHHHH...H.......',
  'H......H............H.......',
  'H......H.......G..P.H.......',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_5: LevelDef = [
  '.........T..................',
  '.........T.......G......E...',
  'BBB......T......BBBBHBBBBBBB',
  '..BB.....T.....BB...H.......',
  '...BB....T....BB....H.......',
  'GE.BBB...T..GBBB....H...G...',
  'BBHBBBB..T..BBBBHBBBHBBBBBBB',
  '..H...BB.T.BB...H...........',
  '..HGE..BBHBB....H.....G.....',
  'HBBBH....H.....BHBBHBBB.....',
  'H...H..............H........',
  'H...H....G.....E...H........',
  'H...HBBBBBBBHBBBBBBHBBBBBHBB',
  'H...........H............H..',
  'H...........H..P.........H..',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_6: LevelDef = [
  'BBBBBBBBBBBBBBBBBBTBBBBBBBBB',
  'B.G...............TB.E.G...B',
  'BXBBBHBBBBH...G...TBBBBBBBHB',
  'BXBBBHBBBBBBBBBBBBBB.BBB..HB',
  'B....H..G.E.....BBBB.BBB..HB',
  'BHBBBBBBBBBHBBBBBBBB.BBB..HB',
  'BH...BBBBBBHBBBBBGGB.BBBG.HB',
  'BH...BBBBBBHBBBBBBBBBBBBBBHB',
  'BH...B....GH....G..E...G.BHB',
  'BH...BBBHBBBBBBBHBBBBBBBHBHB',
  'BH..GBBBH.......HBBBBBBBHBHB',
  'BHBBXB..H....P..H..BB...HBHB',
  'BHBBXBHBBBBBHBBBBBBBBGG.HBHB',
  'BHBBXBHBBBBBHBBBBBBGBBBBBBHB',
  'BHE...HBBGBBH....G..E.....HB',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_7: LevelDef = [
  '..T.........................',
  '..T.................--------',
  '..T..........E......H......H',
  'BBBBBHB....BHBBB...EH....G.H',
  '.....H......H....BBBHBBBBBBB',
  '..E..H...G..H.......H.......',
  'BBBBBHBBBB..H.......H.......',
  '.....H......H.......H.......',
  '..G..H...G..H.......H.......',
  'BBHBBBBBBBBBBBBH....H.BBBB.H',
  '..H............H.G..H.BBBB.H',
  '..H..G.........H----H.B.GB.H',
  'BBBBBBBH............H.BBBBBH',
  '.......H............H......H',
  '.......H.P........G.H..E...H',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_8: LevelDef = [
  '...........T....T...........',
  '...........T....T...........',
  '...G.E...HBT....TBH...E.G...',
  'HBBBBBH--HBT....TBH--HBBBBBH',
  'HB...BH...BT....TB...HB...BH',
  'HB...BH...BT....TB...HB...BH',
  'HB.G.BH...BT....TB...HB.G.BH',
  'HBBBBBH...BT....TB...HBBBBBH',
  'HB...BH...BT....TB...HB...BH',
  'HB...BH---BHBBBBHB---HB...BH',
  'HB...B...HBH....HBH...B...BH',
  'HBEG.B...HBH..GEHBH...B.GEBH',
  'HBBXBB...HBSSSSSSBH...BBXBBH',
  'H.....X..H........H..X.....H',
  'H......XEH....P...H.X......H',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_9: LevelDef = [
  'T...........................',
  'T---------------------------',
  'HB.E...B.............B.....B',
  'H.BBBBB...............BBBBB.',
  'H.B.BBB...............BGBBB.',
  'H.BBBBB.E....E......E.BBBBB.',
  'H.BBB.BXBBBBBBBBBBBBBBBBB.B.',
  'H.BBBBBXBBB.GBB.GBBBBBBBBHB.',
  'H.BBBBBXBBBBBBBBBBBBBBBBBHB.',
  'H.BBBBBXBBBBBBBBBBBBBBBBBHB.',
  'H.BBBBBXBBBB....BBBBBBBBBHB.',
  'H.BBBBBXBBBB....BBBBBBBBBHB.',
  'H.BBBBBXBBBB...GHBBBBBBBBHB.',
  'H...........BBBBH--------H..',
  'H..........SSSS.............',
  'H......P..SSSS......E.......',
]

const LEVEL_10: LevelDef = [
  '..........G..............T..',
  '........HBBBBBBB..G......T..',
  '....G...H......BBBBBB....T..',
  'BBBBBBBBBBH.........G....T..',
  '..........HBBBBBBTBBBBBHBB..',
  'E.........H......T.....H....',
  'BBBBBBBBBBH......T.E...H...G',
  'BBBBBBBBBBHBBBBBBBSS...HBBBB',
  'BBBBBBBBBBH............H....',
  'BBBBBBBBBBH.......G.---H....',
  'BB......BBH.......BB...H....',
  'BB..GG..BBH.....G......H....',
  'BBBBBBBBBBBHBBBBBBBH...H....',
  '...........H.......BBBBBBBBH',
  '....G....P.H...............H',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_11: LevelDef = [
  '.......H....................',
  '.EG....H.................GE.',
  'HBBEG..H...............GEBBH',
  'H..BB..HBBBBTHBBBBBH...BB..H',
  'H...........HHG....H.......H',
  'H...........GHH....H.......H',
  'H...........HHG............H',
  'H...........GHH............H',
  'H...........HHG............H',
  'H...........GHH............H',
  'H...........HHG............H',
  'H...........GHH............H',
  'H...........HHG............H',
  'H...........GHH............H',
  'H.......P...HHG............H',
  'H....HBBBBBBBBBBBBBBBBH....H',
]

const LEVEL_12: LevelDef = [
  '......G.....G...........H...',
  'HBBBBBBBBBBBBBBBBBH.....H...',
  'H.............G...H-----H..G',
  'BBBBBBBBBHBBBBBBBBB.....HBBB',
  'BBBBBBBBHH..............H...',
  'BBBBBBBHH-------H.......H...',
  'BG.GBBHH......E.H..G..E.H..G',
  'BBBBBHH.....HBBBBSSSBBBBHBBB',
  '.....H......H...........H...',
  '.....H......H...........H...',
  '....EH...G..H-----------H..G',
  'HBBBBBBBBBBBH..G.....G..HBBB',
  'H...........H.BBBBBBBBB.H...',
  'H...........H...........H...',
  'H......G....H....P.G....H...',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_13: LevelDef = [
  '............E..........E....',
  'XHXHXHXHXHXHXHXHXHXHXHXHXHXT',
  'XHXHXHXHXHXHXHXHXHXHXHXHXHXT',
  'GHBH.HBHGHBH.HBHGHBH.HBHGHBT',
  'XHBHXHBHXHBHXHBHXHBHXHBHXHBT',
  'XHBHXHBHXHBHXHBHXHBHXHBHXHBT',
  'XHBHXHBHXHBHXHBHXHBHXHBHXHBT',
  '.HBHGHBH.HBHGHBH.HBHGHBH.HBT',
  'XHBHXHBHXHBHXHBHXHBHXHBHXHBT',
  'XHBHXHBHXHBHXHBHXHBHXHBHXHBT',
  'GH.H.H.H.H.H.H.H.H.H.H.H.HBT',
  'HBBBBBBBBBBBBBBBBBBBBBBBBBBT',
  'H.........G.E.G...G.E......T',
  'HSSSSSSSSSSSSSSSSSSSSSSSSSST',
  'HG.......P................GT',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_14: LevelDef = [
  '..H...E....-...E-H....H-...G',
  '.-H...-H-...-..-.H-...H.-..H',
  '-.H..-.H.-....-..H.-..H..-.H',
  'G.H.-..H..-..-...H..-GH...-H',
  '..H-..-H...--....HG..-H....H',
  'H-...-.H-..--..-.H------.-..',
  'H.-...-H..-G.-...H..-...H.-.',
  'H-.-...HG--H..-..H.....-H..-',
  'H.-.-..H--.H...-.H....-.H..-',
  'H-.G.-EH-..H.-..-H-..-..H..-',
  'H.-H..-....H...-...-....H..-',
  'H-.H...-...H..-.-...-...H..-',
  'H.-H.-..-..HG-...-...-..H.G-',
  'H-.H...-.-.H-.-..G-...-.H.-.',
  'H.-H..-...-H.....-.-.-.-H-..',
  '...H.....G.....GP.......H...',
]

const LEVEL_15: LevelDef = [
  'T..........................T',
  'T.....G.E..G.....G..E.G....T',
  'TTTTBBBBBBBBH...HBBBBBBBBTTT',
  '............H...H...........',
  '.......HBBBBBBBBBBBBBH......',
  'G..E..GH.....G.G.....HG.E..G',
  'BBBBBBBH.G.GBBBBBG.G.HBBBBBB',
  '.......H.BBBB...BBBB.H......',
  '....G..H......G......H.G....',
  '..HBBBBBBBBBBBBBBBBBBBBBBH..',
  '..H...........P..........H..',
  '..H.G....GHBBBBBBBHG...G.H..',
  'BBBBBBBBBBH.......HBBBBBBBBB',
  '..........H.......H.........',
  '..G.......H.......H......G..',
  'BSBSBSBSBSBSBSBSBSBSBSBSBSBS',
]

const LEVEL_16: LevelDef = [
  '.........................T..',
  '....................P.....T.',
  '...XBBBBHHBBBBBBHHHHH......T',
  '.........H...B..H.........T.',
  '....G.....H.HB..H........T..',
  '....BG.....HHB..H.......T...',
  '...BBBG.....HB..H......T....',
  '..BBBBBG....HB..H.....T.....',
  'BBBBBBBB....HB..H......T....',
  '.GBBBBB.....HB..H.......T...',
  '...BBB......HB..H........T..',
  '....B.......HB..H.........T.',
  '.......E....HB..H...E......T',
  '.HBBBBBBBBBBBBBBXBBBBBBBBB.T',
  '.BBBBBBBBBBBBBBB.........HBT',
  'BBBBBBBBBBBBBBBB...GGGGGGHBB',
]

const LEVEL_17: LevelDef = [
  'T..........................T',
  'T..........................T',
  'T.........E................T',
  'HBBBXBBBBBBBBBBBBBBBBBBBBBBH',
  'HBBBXBBBBBBBBBBBBBBBBBBBBBBH',
  'H...G...BB--------BB.......H',
  'H.......GBH....E.GBB....E..H',
  'H..BBB..BBH.BBBBBBBB..BBBBBH',
  'H..BGB..BBH.......BB..BBGBBH',
  'H...P...BBH.......BB..BBBBBH',
  'H..BBB..BBBBBBBBHHBB..BBGBBH',
  'H..BBB..BBBBBBBBHHBB..BBBBBH',
  'H..BBB..BB......H.BB.......H',
  'H..BBB..BB.....GH.BB....G..H',
  'BBBBBBBBBBHBBBBBBBBBHBBBBBBB',
  'BBBBBBB..GHBBBBBB.G.HBBBBBBB',
]

const LEVEL_18: LevelDef = [
  '...T........................',
  '...T......G.........G......G',
  'HXBH....HBBBH.....HBBBHB..BH',
  'H..BBBBBB...HBBBBBH...H..G.H',
  'HG.E........H.....H...BBBB.H',
  'HXBBBB.........BBBHB.......H',
  'H.SBBBB.......BB........HB.H',
  'H.SBBBBB.....BB.......HBH..H',
  'H.SBBBBBBBBBBB....G...H...BB',
  'H.SBBBBBBBBBBB...BBB..H.....',
  'H.S....BBB.BBB........H...EG',
  'H.S..G.BB.G.BB.....E..H...BB',
  'H.SHBBBBBBBBBBBHBBBBBBH...BB',
  'H..H...........H......H...BB',
  'H..H.......P..........H...BB',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_19: LevelDef = [
  '............HBBH............',
  '..........EGHBBHGE..........',
  '..........HBBBBBBH..........',
  '.........GHBBBBBBHG.........',
  '........HBBBBBBBBBBH........',
  '......EGHBBBBBBBBBBHGE......',
  '......HBBBBBBBBBBBBBBH......',
  '.....GH...GGGGGGGG...HG.....',
  '....HBBBBBBBBBBBBBBBBBBH....',
  '...GHBBBBBBBBBBBBBBBBBBHG...',
  '..HBBBBBBBBBBBBBBBBBBBBBBH..',
  '..HBBBBBBBBBBBBBBBBBBBBBBH..',
  '..H......................H..',
  '..H......................H..',
  '..H..........P...........H..',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_20: LevelDef = [
  '.............EG.............',
  '...........BBBBBBBBH...E.G..',
  '.......E.G.........HBHBBBBBH',
  '.....GBBBBBH.......H.H.....H',
  'BBBXBBB....H-------H.HG....H',
  '...........H.......H.BBBBBBB',
  '.G.........H.......H........',
  'BBBHBBBBBBBH.......H--------',
  'G..H...E...H....G..H.......G',
  'BBBBBBBBB..BBBBBBBBH....BBBB',
  '.......G...G.......H........',
  'BBBBBHBBBXBBBH..G..H...G....',
  '.....H.......BBBBBBBBBBBBBBH',
  '.....H.....................H',
  '.....H.G...P......G........H',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_21: LevelDef = [
  'SSSSSSSSSSSSSSSSSSSSSSSSSSTB',
  'H----------------------HTTTB',
  'H..H.....BB..E...G.....HTG.B',
  'H..H.BBBBBBBBBBBBBBBBBBBBBHB',
  'H..H.BBB............G.....HB',
  'H..H...B.BBBBBBBBBBBBBBBBBBB',
  'H..H..HB...G..B.G.B.G.B.G..B',
  'H..H..HBBHBBBBBBBBBBBBBBBBBB',
  'H..H--H..HBBBBB.BBBBB......B',
  'H..H..H..H....B.GB.....E...B',
  'H..H..H..H--H.BBBBH--BBBBBBB',
  'H..H..H..H..H.....H..BBBBBBB',
  'H..H..H..H..H--H..H..BBBBBBB',
  'H..H..H..H..H..H.BHBBB.GGG.B',
  'H..HP.H..H.EH..H..HBBBHBBBBB',
  'BBBBBBBBBBBBBBBBBBH.GGHBBBBB',
]

const LEVEL_22: LevelDef = [
  '.......G....G...............',
  'GGBBBBBBBBBBBBBBBBH.........',
  'BB..........G..G..H.........',
  '.........HBBBBBBBBH..G...G..',
  '.........H........HBBBBBBBB.',
  '....G.EG.H..................',
  '...HBBBBBBH------.....G.....',
  '...H......H......HBBBBBBBBBH',
  '.G.H......H......H.........H',
  'BBBH....E.H..E.G.H.......G.H',
  '......HBBBHBBBBBBH....HBBBBB',
  '......H--------....G..H.....',
  '....G.HG.......HBBBBBBH...G.',
  'BBBBBBBH.......H......HBBBBB',
  '.......H.......H............',
  '.......H..G..P.H......G.....',
]

const LEVEL_23: LevelDef = [
  '...SSSSSSSSS...........T....',
  '..S.........S..........T.SS.',
  '.S...GG.E....BH........T.SS.',
  'SSBBHBBBBBBBBSSH....E..TGSS.',
  'SBBBHBBBBBBBBBBBHBBSSSBHSSSS',
  'SBBHHHB-------BHHHB----H---H',
  'SBBH.HB..G....BH.HB.G....G.H',
  'SBBH.HB..P....BH.HB........H',
  'SBBHGHBBBBHBBBBHGHBS......SH',
  'SBBBBBBBBBHBBBBBBBBBBBBBBBBH',
  'S......BBHHHBB..G....G...G.H',
  'S------BHH.HH--------------H',
  'S.G....BH...H............E.H',
  'S.......H...H..BBBBBBBBBBB.H',
  'SSSS....H...H.BBB.GBB..G.BBH',
  'SBBBBBBSHG.GH..BBBBBBBBBBBBB',
]

const LEVEL_24: LevelDef = [
  '................T...........',
  '...............TT...........',
  '..............TT............',
  '.............TT.............',
  '............TT..............',
  '............T...............',
  '..........HBBH..............',
  '..........HBBHG.............',
  '.......HBBBBBBBH..E.........',
  '.BH..E.HB.G.G.BH.BHBH.......',
  '..BBBHBBBBBBBBBBBBHBBBH.....',
  '...BB.G..BBBB.G...HG..BBH...',
  '....BBBBH..G.BBBH.HBBH.BH...',
  '.....BGBHBBBH.G.H.HGBHGBH...',
  '..E...BBBBBBBBBBBBBBBBBBH.P.',
  'SSSSSSSSSSSSSSSSSSSSSSSSSSSS',
]

const LEVEL_25: LevelDef = [
  '....S.....S.....S.........TS',
  '....S.....S.....S...G.....TS',
  '....SXBBBBS.....SBBBB..BBBTS',
  'BBB.........BBBHE..G.....GTS',
  'BBBBBBBBBBBH...HBBBBBBBB.BHS',
  '.......P...H.BBHB...G....BHS',
  'BHBBBBBBBBBH.GBHB.BBBBBH.BHS',
  'B--------BBH.BBHB.B....H.BHS',
  'B..B..B.GBBH...HH.B.BBBH.BHS',
  'B..B..B..BHHBBBBHBBGBBBH.BHS',
  'B..B.GB..BHB......B.BBBH..HS',
  'B..BBBB..BHB.BBBB.B....HBHHS',
  'BHBB..BBHHHB.BGBB.BBBBBBBH.S',
  'BH...SSBHHBB...B..BBG....HBS',
  'BH...S...HBBXBBBBXBBBBBBBHBS',
  'BHBBB....H.....E.........H.S',
]

const LEVEL_26: LevelDef = [
  '..........................T.',
  '.....E....................T.',
  'HBBBBBBBBBBH..E..G.....G..T.',
  'H..........HBBBBBH...BBBHBBB',
  'H.G......G.H....SH......H...',
  'H.B..BBB.B.H.GG.SH....E.H...',
  'H.B.BBB..B.H.SS.SBBBBBBBBBSS',
  'H.B..BBB.B.H.SS...........SG',
  'H.B.BBB..B.H.S-------..G..SH',
  'H.BG.BBB.B.H.SG......BBBBHSH',
  'H.BBBBB..B.H.SS..........H.H',
  'H.BBBBBBBB.H.SS....G.....HBB',
  'H..........H.SS.BBBBBB...H..',
  'HSSSSSSSSBSSSSS..........H..',
  'H.............P..........H..',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_27: LevelDef = [
  'T..........................T',
  'T......P............E......T',
  'T...SBHBS----------SBHBS...T',
  'T...SGH.S.G......G.S.H.S...T',
  'T.SBB.H.BBS......SBB.HGBBS.T',
  'TTSG..H..GS.G...GS.G.H.BGSTT',
  'STBBB.H...BBS..SBBBBBH.B.BTS',
  'S.....H.....S.GSG....H.B..GS',
  'S.....HBBBBBSHBSBB..GH.BB.BS',
  'S.G.E.H...E..H.....BBH.....S',
  'SHBBBBH...SBBHBBBS...H...BHS',
  '.HS.G.H...B..H.G.B...H..ESH.',
  '.HSBB.H.BBB..H...BBB.H.BBSH.',
  '.H.GS.H.S....H....GS.H.SG.H.',
  '.H...BBB.....H......BBB...H.',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_28: LevelDef = [
  '.............T..............',
  '-----------..T..............',
  '..G....G.SH..T.G............',
  'BBBBBBBBBSSSSSSSH..GHSH.....',
  'BSBSBSBSSSSS...SSSSSSSH.....',
  '..........SS..G......SH.EG..',
  '--------H.SSBBBBBH...SSBBBBH',
  '........H.SS.....HE....BBBBH',
  '........H.SS.BBBBBBBBH.BBBBH',
  '.G....G.H.SS.B......BH.BBBBH',
  'BBBE..B.H.SS.B...G..BH.BBGBH',
  'BBBBBBB.H.SS.BBBBBBBBH.BB.BH',
  '........H....B..G...BH....BH',
  'BBBBBBBBBBBBBB.HBBH.BBBBBBBH',
  '..........P....H.GH........H',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_29: LevelDef = [
  '..E.--.-.............E......',
  'BBBB..H...-.........BBH.....',
  'BBBB..H.BB.-...E...-BBH.....',
  'BGGB..H.BB-.BBBBBBB..-H.....',
  'BBBB..H.....BBBBBBB.H.HBBB..',
  '......H---..BBBBBBB.H..BGB..',
  '....-.....H.BBBBBBB.H..BBB..',
  '.....BBBB.H.BBGGGBB.H.......',
  '...-.BBBB.H.BBBBBBB.H.......',
  'BBB-.BGGB.H-.....-.-H.......',
  'BGB..BBBB.H.-...-.H..BBBB...',
  'BBB.......H...P...H..BBBB...',
  '..........H..BBB..H..BGGB...',
  '...BB.....H..BGB..H..BBBB...',
  '...BB.....H..BXB..H.........',
  '..........H.......H.........',
]

const LEVEL_30: LevelDef = [
  'S..........................T',
  'S.....GGGGE.E.E......P.....T',
  'SBBBBBBBBBBXBBBBBBBBBBBBBBBH',
  '...........................H',
  '....S.G..G.......G......GS.H',
  '....SBBBBBBBXBBBBBBBXBBBBS.H',
  '...........................H',
  '......S..G....G.....G..S...H',
  '......SBBBXBBBBBBXBBBBBS...H',
  '...........................H',
  '.......S..G.....G....GS....H',
  '......SSBBBBBBBBBBBBBBS....H',
  '...........................H',
  '...........................H',
  'GGGG...E..........E.....HS.H',
  'BBBBBBBBBBSSSSSSBBBBBBBSSS.H',
]

const LEVEL_31: LevelDef = [
  '.............T..............',
  '.............T..............',
  'G............TT............G',
  'BH.H----------T---------H.HB',
  'BBHH.E................G.HHBB',
  'BBBH.H------.---------H.HBBB',
  'BBBBHH.G..............HHBBBB',
  'BBBBXH.H------.-----HEHXBBBB',
  'BBBBXBHH..........G.HHBXBBBB',
  'BBBBXBBH.H---.----H.HBBXBBBB',
  'BBBBXBBBHH.G......HHBBBXBBBB',
  'BBBBXBBBBH.H--.-H.HBBBBXBBBB',
  'BBBBXBBBBBHH....HHBBBBBXBBBB',
  'BBBBXBBBBBBH....HBBBBBBXBBBB',
  'BBBBXBBBBBBBHPGHBBBBBBBXBBBB',
  'BBBBE.......HBBH........BBBB',
]

const LEVEL_32: LevelDef = [
  '............................',
  'BBBTBBBB.........------.E...',
  '...T.--..E............SSSSSH',
  '...HB..BBBBBHBBBBBB---...B.H',
  'HBBBB..BG---H-----B...BBBBHB',
  'H......BBBB...BBBHB...BG..H.',
  'H......B----H----HB...B-..H.',
  'H.PB...BHGBGHGBHGHB...B...HG',
  'BHBB...BBBBBBBBBBBB...BBHBBB',
  '.H....GB.....G....B.....H...',
  '.H....BB...BBBH...B.....H...',
  '.H..GB.B......H...BG..HBBBBB',
  '.H..B..B...G..H...BB..H.....',
  '.HGB...B.HBBBBBBH.B.BGH.....',
  '.HB..G.B.HB..G.BH....BH.....',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_33: LevelDef = [
  'BBBBBTBBBBBBBBBBBBBBBBB.BBBB',
  '....BTB.-------............B',
  'TBBT.TB.BG...BHB.........E.B',
  'T.BBBBB.BBBBBBHBBBBBG.BHBBBB',
  'BT....G---BBBBHBBBBBBBBHB.BB',
  'BBBBBBB...B..BHBBB.BBBBHB.BB',
  '.......E.....BHBBB.BB.BHBG.B',
  'HBBBBBBBHBHG.BHBBB.BB.BHBBBB',
  'H.......HBBBBBHBBBG.B.BHBB.B',
  'H.........BBBBHBBBBBB.BHBBGB',
  'H.......B.....H........H...B',
  'HBBBHBBBBHBSBSBSBSBSBSBHBSBS',
  'HBBBHBBBBHBBBBBB..BBBBBHBSBS',
  'H...H....HBBBBBBB..BBBBH....',
  'HBBBBBBBBHBBBBBBBBG.BBBBBBBH',
  'HP.......H.G.BBBBBB..E.....H',
]

const LEVEL_34: LevelDef = [
  '.--------GGBBBBBBGG--------.',
  'H.......GBBBHHHHBBBG.......H',
  'H......GBBHHHEEHHHBBG......H',
  'H......BBHH......HHBB......H',
  'H.....GBHH........HHBG.....H',
  'H.....BBHG........GHBB.....H',
  'H.....BHHG........GHHB.....H',
  'H.....BHGG........GGHB.....H',
  'H.....BHHG........GHHB.....H',
  'H.....BBHG........GHBB.....H',
  'H......BHHG......GHHB......H',
  'H......BXHHGG..GGHHXB......H',
  'H.......XBHHHGGHHHBX.......H',
  'H........BBBHHHHBBB........H',
  'HP......E..BBBBBB..E.......H',
  'BBBBBBBBBH........HBBBBBBBBB',
]

const LEVEL_35: LevelDef = [
  'T............BB............T',
  'T............SS............T',
  'T.G.......G..BB..G.......G.T',
  'SBSBSBSBSBSBHSSHBSBSBSBSBSBS',
  '...G.....G..HBBH..G.....G...',
  'HSBSBSBSBSBSBSSBSBSBSBSBSBSH',
  'H...G...G....BB....G...G...H',
  'SBSBSBSBSBSBHSSHBSBSBSBSBSBS',
  '....GE.EG...HBBH...GE.EG....',
  'HSBSBSBSBSBSBSSBSBSBSBSBSBSH',
  'H..G.....G...BB...G.....G..H',
  'SBSBSBSBSBSBHSSHBSBSBSBSBSBS',
  '..G.......G.HBBH.G.......G..',
  'HSBSBSBSBSBSBSSBSBSBSBSBSBSH',
  'H............P.............H',
  'BSBSBSBSBSBSBSBSBSBSBSBSBSBS',
]

const LEVEL_36: LevelDef = [
  '....G....G.....G.......EG...',
  'HBBBBBBHBBB.BBBBBHBBB.BBBBBH',
  'H......H.........H.........H',
  '.H......H..-....H.........H.',
  'H......H..-.-....H.........H',
  '.H......H-...-..H.--------H.',
  'H------H......-..H.........H',
  '....E...H-.....-H.........H.',
  'BBBBBB.H..-...-..H....EG.G.H',
  'BB.BBB..H..-.-..H....-BBBSSS',
  '.G...G.H....-....H...-BBBSSS',
  'BBXBBB..H..-.-..H....-BBBSSS',
  'BBXB.B.H..-...-..H...-BBGGSS',
  '..G.G...H-.....-H....-SSSSSS',
  'BBBBBB.H....G.P..H.G..SSSSSS',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_37: LevelDef = [
  'T...........................',
  'T......E....................',
  'TBBBBBBBBBBSSSSSSBSSSSBSSSSH',
  'G.....................H....H',
  'BB.........S...G....G---G..H',
  'BBBBBHHBHHBBBBBBBB..B...B..H',
  '....BHH.HHB.SSBBBB.....E...H',
  '....BHHGHHB.S.BBBB.BBBHBBBBH',
  '....BBBBBBB.SGBBB.....H....H',
  '......................H....H',
  '.......P.......BHBBBBBHSSSSH',
  'BBHBBBBBBBBHBBB.H.GG..H....H',
  '..H........H....H.SS.....BBH',
  '..HBBGB....H..BBB.SSBBBBBB.H',
  '..HBBBB...EH...G..SS.......H',
  'BBBBBBBBBBBBBBBBBBSSBBBBSSSS',
]

const LEVEL_38: LevelDef = [
  'T..........................T',
  'T..........................T',
  'BBBBBBHBBBBHE.EHBBBBHBBBBBBB',
  '.-....H....HSHSH....H.....-.',
  'H.BBBBB......H...G..BBBBBB.H',
  'H.BBBBB..BHHHHHHHB..BBBBBB.H',
  'H.BBBGB..BHSSSSSHB..BBGBBB.H',
  'H.BBBBB..BHHHHHHHB..BBBBBB.H',
  'H.........-------..........H',
  'H.E...H......S......H....E.H',
  'HSSSSSH....GSSSG....HSSSSSSH',
  'H.....H....SSSSS....H......H',
  'HBBBBBH...SSSSSSS...HBBBBBBH',
  'H.....H.GSSSSSSSSSG.H......H',
  'HSSSSSH.SSSSSSSSSSS.HSSSSSSH',
  'G.....HSSSSSSSSSSSSSH..P...G',
]

const LEVEL_39: LevelDef = [
  'BBB..T.BB....BB....BB.T..BBB',
  'BBBB.TBBBB.EBBBB.EBBBBT.BBBB',
  'H..BBHB..BBHB..BHBB..BHBB..H',
  'H...BH--H.BH...GHB.H--HB...H',
  'H.EBBBBGHBBBBHHBBBBHGBBBB.PH',
  'HBBB..BBHB..BHBB..BHBB..BBBH',
  'HBB....BHG...HB...GHB....BBH',
  'HBBB..BBBBHHBBBBHHBBBB..BBBH',
  'H..BBHB..BBHB..BHBB..BHBB..H',
  'H...BH....BH...GHB....HB...H',
  'H..BBBBHHBBBBHHBBBBHHBBBB..H',
  'HBBB..BBHB..BHBB..BHBB..BBBH',
  'HBB....BH....HB....HB....BBH',
  'HBBB..BBBBHHBBBBHHBBBB..BBBH',
  'H....G....HH.G..HH....G....H',
  'HBBBBBBBBBBBBBBBBBBBBBBBBBBH',
]

const LEVEL_40: LevelDef = [
  'T..........BBBBBBBBBBBBBBBBB',
  'T..........BBBBBBBBS.------B',
  'T....G...HB....G...SH.B.G..B',
  'BBBBBBBBBHSBBBBBBB.SH.BBBBBB',
  '....G....HS....G...SH.BBBBBB',
  'HBBBBBBBBBS.BBXBBB.SH.BBBBBB',
  'H....EG...S......G.SH...E...',
  'BBBBBBBBBHS.BBXXXB.BBBBBBBBH',
  '.G.......HS....G...........H',
  'HBBBBBBBBBS.BBXBBB.........H',
  'H..G......S......G.........H',
  'BBBBBBBBBHS.BBXXXB..BBBBB..H',
  '........GHS......G..B..GB..H',
  'HBBBBBBBBBS.BBXBBB....HBB..H',
  'H...E.......P.........HB.G.H',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_41: LevelDef = [
  '....--G.--------E-----.-----',
  '...H.GBG........H-.B.-H..GGG',
  'GPH.GB.BG......H-.BBB.-H..GG',
  'BB.GB...BG....H-.B...B.-H..G',
  '.E.X..B..B...H-.BB...BB.-H.E',
  'HBB..BBB..SSS-...BGGGB...-BH',
  'H...B...B...G...HHBBB......H',
  'H..-.BBB...GH..HBBHB.......H',
  'H...-.B...GH...HGGH.-------H',
  'H....-...GH...HSSSSH.......H',
  'SSSH..---H....HG..GH.------H',
  '...H.........HBBBBBBH......H',
  'BBBHBBBH.....HG....GH.-----H',
  '.......H....HSSSSSSSSH.....H',
  '.......H..E.HG...E..GH.----H',
  'BBBBBBBBSSSSSBBBBBBBBH.....H',
]

const LEVEL_42: LevelDef = [
  '..G.......G..........G....G.',
  'HBBB....HBBB....HBBBBBBBBBBH',
  'H.G...G.H.....G.H.G....G...H',
  'HBBBHBBBH...BBBBBSBBSBBBBSBB',
  'H...H..EH...---------------.',
  'BBBBHBBBBBBH......G...GE...H',
  '....H......H.SBBBBSSSSSSBBBH',
  '....HSSSSS.H.S......G..G...H',
  'B...H..G.S.H.S...SSSSSSSSS.H',
  'BGGSSSBBBS.H.S...S..G.G..S.H',
  'BBBSSSBBBS.H.S.G.S.HBBBBHS.H',
  '..G..G.....H.SSXSS.H....HS.H',
  'BBBBBBBBB..H.S.....H...EHS.H',
  '..G.G...S..H.SBBBBBBBBSSSS.H',
  'BBBBBBH.SSSSBBBBS...G..G..PH',
  'BBBBGBH...........HBBBBBBBBB',
]

const LEVEL_43: LevelDef = [
  '............................',
  '..T.......................T.',
  '..HBBBBBBBBBBBBBBBBBBBBBBBH.',
  '..H.HBB...G...G.E.G...BBH.H.',
  '..HBBBHBBBBBBBBBBBBBBBHBBBH.',
  '..H.H.H.BBB.G...GEBBH.H.H.H.',
  '..BBHBBBH.HBBBBBBBH.HBBBHBB.',
  '..H.H.H.H.H.HBBBH.H.H.H.H.H.',
  '..HBBBHBBBH.H.G.H.HBBBHBBBH.',
  'G.H.H.H.H.HEHSSSHEH.H.H.H.HG',
  'BBBBHBBBHGHSHSSSHSHGHBBBHBBB',
  'BBH.H.H.HSHSHSSSHSHSH.H.H.HB',
  'BBHBB.HSHSHSHSSSHSHSHSH.BBHB',
  'BBH.HSHSHSHSHSSSHSHSHSHSH.HB',
  'BBHSH.H.H.H.H..PH.H.H.H.HSHB',
  'BBBBBBBBBBBBHBGBHBBBBBBBBBBB',
]

const LEVEL_44: LevelDef = [
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBT',
  'B...HHHHHHHHHHHHHHHHHHH...BT',
  'B.P.H.HHH....H...HH...H.E.BT',
  'BBBBH.HHH.HH.H.HH.H.HHHBBBBT',
  'B...H.HHH.HH.H.HH.H...H...BT',
  'B.E.H.HHH.HH.H.HH.H.HHH.E.BT',
  'BBBBH...H....H...HH...HBBBBT',
  'HHHHHHHHHHHHHHHHHHHHHHHHHHHT',
  'H.G.H.G.H.G..H..G.H.G.H.G.HT',
  'HHHHHHHHHHHHHHHHHHHHHHHHHHHT',
  'H...H.H.H.HH.H.HH.H...H...HT',
  'H.H.H.H.H..H.H..H.H.HHH.H.HT',
  'H..HH.H.H.H..H.H..H...H..HHT',
  'H.H.H.H.H.HH.H.HH.H.HHH.H.HT',
  'H.H.H...H.HH.H.HH.H...H.H.HT',
  'HHHHHHHHHHHHHHHHHHHHHHHHHHHT',
]

const LEVEL_45: LevelDef = [
  'SSSSSSSSSSSSSSS..T.SSSSSSSSS',
  '..EH......H---...T.H......G.',
  'SSSTBBSSSSSBXBSSST.HSSSS.HSB',
  'S--H.......H----H..H...BBBBB',
  'S..H.......G.BGBHE.H..G...BB',
  'G.XH.......H....SBH.SSBBBBSB',
  'SBXH-------H-----SH-------HS',
  'BG.S.......H...GHSSS......HB',
  'SSXB....GGGH....HS----..G.HH',
  'S..........H....HSH.G...XBSH',
  'BBBXBB.....H.P..HSH........H',
  'BH----.HSBBBSBBXSSH........H',
  'BHG...BH........HBH..SBBBB.H',
  'BHS--BBBH.......HSH..B.G.S.H',
  'BH..BBBSBH..E...H.H...BSSBSS',
  'SBBBBBSSSSBBBBBBBBBBBBBBSBBB',
]

const LEVEL_46: LevelDef = [
  '.G...................T......',
  'BBBBH............E...T......',
  '..G.H..........HBBBBBBH...G.',
  'BBBBBBBBHBBBBBBH.....BBBBBBB',
  '........H......H.G........G.',
  '.....G..H......HBBBBBBBBBBBB',
  'BHBBBBBBH...G..H............',
  '.H...G..HSSSSSSH......G.....',
  'BHBBBBBBH......BBBBBHBBBBBBH',
  '........H.E....G....H......H',
  '.G......HBBBHBBBBBBBSSSSSSSS',
  'BBBHBBBBB...H..G......G.E...',
  '...H.......HBBBBBBBBHBBBBBBB',
  '...H-------H........H.......',
  '...H.........P......H.....G.',
  'BBBBBBBBBBBBBBBBBBBBBBBTBBBB',
]

const LEVEL_47: LevelDef = [
  'S...............SSSSSSSSSSST',
  'SE........E.....S..G.S.....T',
  'SS------BBBBBH.PS.HS.SHSBBBT',
  'SBBBBB...G..BBBSS.HS.SHSBBBT',
  'S....BBBBBB.......HS.SHS...T',
  'BBBH......BBBBH.G.HS.SHS.G.T',
  'B.BBBSBH......HBBBSS.SHSBBBT',
  'B..G..BBSBH...H....S.SHSBBBT',
  'BBBBB....BBBSBH....S.SHS...T',
  'B.G.BSHB.....BBSBBHS.SHSGG.T',
  'BBB...HBBSSB..G..SHS.SHSBBBT',
  'B.BSBBH....BBBSSBSHS.SHSBBBT',
  'B...BBBSBBH..G...SHS.SHS.BBT',
  'B.HBB...GBBBSSBHBSHS.SHS..BT',
  'B.HB...........H.GHS..H...GT',
  'BGHBSBBBBSBBBBBSBBSSBBSBBBBB',
]

const LEVEL_48: LevelDef = [
  '............G...............',
  '.-------.BBBBHP.............',
  'H..........G.H....G......G..',
  'H........HSSSS.BBBBBBBHBBBBB',
  'H........H.G..........H.....',
  'HBBBBBBH.BBBBH........H.....',
  'H......H...G.HEHBBBBBBBBBBBH',
  'H......H.HSSSS.HSSSSSSSSSSSH',
  'H....GHB.HG....HS.....G...SH',
  'H....HB..BBBBH.HSHSSSSSSSHSH',
  'H..GHB......GH.HSHS...G..HSH',
  'H..HB....HSSSS.HSHSSSSSSSSSH',
  'H.HB.....H.G...HSH....G....H',
  'HHB......BBBBH.HSSSSSSSSSSSS',
  'HH..E........T.H....E.......',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_49: LevelDef = [
  '.....-.....-.-......-..G..G.',
  '-...-.-...-.H.-....-.HBBBBBB',
  '.-.-...-.-..H..-..-..H......',
  '..-.....-...H...--...H..E...',
  '.G...G..G...H...-....HSSSSSH',
  'SSSSSSSXSSSSSSH-.....HS.G.SH',
  '..............S......HSHSGSH',
  '.............GS..P.G.HSHSGSH',
  'HBBBBBBBBBBHBSSHBBBB-HSHSGSH',
  'H.....E....HBBHH.....HSHSGSH',
  'H....BB....HBBH...GE..SHSGSH',
  'H.BBB..BBB.HBBSSBBBBBHSH----',
  'H.BBB..BBB.HBB.......H......',
  'H.BBBGGBBB.HB.....--GH.BBBB.',
  'H.G.GBBG.G.HBB..HB..BHBBGGBB',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_50: LevelDef = [
  'H...-..................H----',
  'H....H.................H.S..',
  'H....H.............E...H.SGG',
  'H.G..HBBBB..G..GHBBBBBXBHBBB',
  'HBB..H...BBBBBBBBB......HHBX',
  'H....H...................HHX',
  'H.....H-------------------HH',
  'H.....H....................H',
  'H.....H.G.......E...G.....GH',
  'H.....BBBBBHSSSSSSSSSSBBXBBB',
  'H---.......H..........---...',
  '...EG......H.........H......',
  'BBBBBBBBBH.H...G.....H-...G.',
  '........BBBBBHSSSHBBBB.BGBBB',
  'G.......P....H...H...E.BBBBB',
  'BBBBBBBBBBBBBH...HBBBBBBBBBB',
]

const LEVEL_51: LevelDef = [
  'BSBSSB.............TSBSSBBBS',
  'BBSSBB.............TBSSBBBSS',
  '...SBSB..G......G..TBS.....S',
  'HB...SBBSBBBSHBBS..TBS.BSH.S',
  'HBS..SBSSBBBSH.BB.GTS..BSH.S',
  'HBB.....SBBSSH..BSBBB.GBSH.S',
  'HSBBG....BSSBH........BBSHG.',
  'HBSBBBB...SBBH..-------BSSBH',
  'H.SSBSBBG..BSH.G.......BS..H',
  'H.....HBB...SSBSSBS....BS..H',
  'SBBBSSHSBB............GBS..H',
  'BSBSSSHBSBBG...E....GBBBS..H',
  '...G..HSSBBBXSSSSSSXBBBSSHBB',
  'HBSBBBSS...E.........P...HSB',
  'HSBBBS..HBBSSBSSBBSBSSBBSSSB',
  'H...G...H............E...SBS',
]

const LEVEL_52: LevelDef = [
  '.........H..................',
  '.........H......G....E......',
  '----..G..T.....SSSSSSSSSSSSH',
  'H..SSSSSSS.................H',
  'H.........-----..-----.HSSSS',
  'H---------........H....H....',
  '....E..........G..HB...H....',
  'HSSSSSSSSSSSSSSSSSSB...SSSSH',
  'H.........................HH',
  'H......G......G.....E..S..H.',
  'SSSSBBSSSSH.BSSBSSSSSSSS..H.',
  '..........H...............H.',
  '.......G..H......G........H.',
  'HSSSSSSSSSS.SSSSSSSS......H.',
  'H...................------H.',
  'H..........P........E.......',
]

const LEVEL_53: LevelDef = [
  '............................',
  '.........E.....E........G.GT',
  '......HBBBBBBBBBBBBBB..HBBBB',
  '......H.BBBBBBBBBBBB..HBBBBB',
  'HBBBBBB..BGBBGBBGBB..HBBBBBB',
  'HBBBBBBB...........EHBBBBBBB',
  'HBBBBBBBBBBBBBXBBBBBBBBB....',
  'HBBBBBBBBG.G....G.GBBBBB.GG.',
  'HBBBBBBBBBXBBBXBBBBBBBBBBBBB',
  'H.......E..........GBBBBBB..',
  'H..HBBBBBHBBBBBH..-HBBBB..GH',
  'H..H..H..H..H..H...BBB..GHBB',
  'H..HGGHGGHGGHGGH...B..GHBBBB',
  'H..HBBBBBHBBBBBH....GHBBBBBB',
  'H..............P...HBBBBBBBB',
  'HBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_54: LevelDef = [
  'T..............BBBBBBBBBBBBB',
  'T..G.....G.....BBBBBBBBBBBBB',
  'BBBBBBBBBBBBBBH..G..........',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBH',
  '.....G.E...E.G.............H',
  'HBBBBBBBBBBBBBBBBBBBBBBBBBBB',
  'H........G..........G.......',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBH',
  '....G........G......G......H',
  'HBBBBBBBBBBBBBBBBBBBBBBBBBBB',
  'H...G..E.E..E.....G.........',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBH',
  '...G......G......G......G..H',
  'HBBBBBBBBBBBBBBBBBBBBBBBBBBB',
  'H.....G...........G..P......',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_55: LevelDef = [
  'BBBBBBBBBBBBT.BBBBBBBBBBBBBB',
  'B---------B.T..B---------B..',
  '.BG..H..GB..T...BG..H..GB...',
  '..BG.H.GB...T....BG.H.GB....',
  '...BGHGB....T.....BGHGB.....',
  '....BHB.....TSSSSSBBHB......',
  '.P..BHB.....TS...G.BHB..E...',
  'BBBHBHBBBBBBXBBBBBBBHBBBBBBH',
  '...H.H.E............H......H',
  'HBBSBHBBBBBBBBBBBBBBHBSBBBBB',
  'H---BHB------------BHB......',
  'H.GB.H.BG........GB.H.B.....',
  'HGB.GHG.BG......GB..H..B....',
  'HB.GBHBG.BG..HBBB...H...B.G.',
  'H.GBBHGBHHBSHBSB..E.H..G.BBB',
  'BBBBBBBBBH..H.GBBBBBBBBBBBBB',
]

const LEVEL_56: LevelDef = [
  'GGG----GGG.GGG-----------GGG',
  'BBB....BBBHBBB...........BBB',
  'BBB....BBBHBBB...........BBB',
  'BBB....BBBHBBB....GGG....BBB',
  'BBB....BBBHBBB....BBB....BBB',
  'BBB....BBBHBBB....BBB....BBB',
  'BBB....BBBHBBB....BBB....BBB',
  'BBB....BBBHBBB....BBB....BBB',
  'BBB....BBBHBBB....BBB....BBB',
  'BBBG--GBBBHBBBG--GBBBG--GBBB',
  'BBBBGGBBBBHBBBBGGBBBBBGGBBBB',
  'BBBBBBBBBBHBBBBBBBBBBBBBBBBB',
  '.BBBBBBBB.H.BBBBBBB.BBBBBBB.',
  '..BBBBBB..H..BBBBB...BBBBB..',
  '...E.....PH..........E......',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_57: LevelDef = [
  'BTBBBBBBBBBBBBBBBBBBBBBBBBBB',
  'BT------------------------.B',
  'BTBSSSBSSSBSSSBSSBSHBS---BHB',
  'BTB....G....G...G..H...GHBHB',
  'BTGHSSSSSSSSSSSSSSSSSSSSHSHB',
  'BTBHB----------------S.GHBHB',
  'BTGHB.SSSSSSSSSSSSSSSSBBBBHB',
  'BTBHB.S.GGGGGGGGGGGG...GBGHB',
  'BTGHB.SBBBSSSSSSBSSSSSHBBBHB',
  'BTBHB.....E...........HGBGHB',
  'BTGHBSSSSSSSSSSSBBSSSSHB.SHB',
  'BTBH------------------..HBHB',
  'BTBSSBBSSHSSBSBSSHSSSSSSHGHB',
  'BT.E.....H.SS....H..E..GHBHB',
  'BSSSBSBBBSSSSHSSBSBSSBBSSBHB',
  '.P...........H............HB',
]

const LEVEL_58: LevelDef = [
  'BBBBBBBBBBBBBBBBBBBBB.....TB',
  'B.PBB---.SS...G...........TB',
  'B.BS..G.HSSBBBBBBHH.HBH.H.TB',
  'B.B.....H....SSB.HHGH.H.H.TB',
  'B.BHBBBBSBBG...B.HH.H.HBH.TB',
  'B.BHB......SBB...HH.H.H.H.TB',
  'BG.HB...G..BSB.HB.H.H.H.H.TB',
  'BBHHBBXBSBBBSB.HBGBTBBHBH.TB',
  'BBH......E.....HBXBTB.H.H.TB',
  'BBHBBSBBBBBBBSHHH.BTB.H.H.TB',
  'BBH.BSBBBBBBBSHH..BTB.H.HEHB',
  'B.H..S..G....SH...BTBHHBBBHB',
  'B.HHBSBBBBBBBSH.G.BTBHE...HB',
  'B.BHBSBBBBBBBSHSSSBTBBBB..HB',
  'B.BHB.....G..SSB...T...B..HB',
  'B.GH.BSSSSSSSSSB.E.T...BBBBB',
]

const LEVEL_59: LevelDef = [
  '...--.G.........-G....G.....',
  '..H..BB........H.BB...BBH...',
  '..H........GE..H........H..G',
  '.GH--......BB.GH..EG....HHBB',
  'BBH..HGE.....BBH..BB...G.H..',
  '...G.HBB.......H......BB.H..',
  '..BB.H-.--EG---H.........H..',
  '..G....H..BB....G...G-...HG.',
  '.BB....H.......BB..BB.HGHBB.',
  '....-.GH..G...........HBB...',
  '...H.BBH..BB...G......H.....',
  '.G.H.....G....BB.G....HG....',
  'HBBH....BB.......BB...HBB...',
  'H...........................',
  'H.............P.............',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_60: LevelDef = [
  '...............-----........',
  '..........----H.....EG..G...',
  '.....----H......E.G.BBBBBBBH',
  '.---H.........G.BBBBB..G..BH',
  'H.........PG.BBBB...GEBXBHBH',
  'H..XBX.BB.BBBB..G.BXBBB.BHBH',
  'H..G.G.G..B..G.BBXB..G..BHBH',
  'H.BB.XBX..B.BBBB...GBBBHBHBH',
  'H..G.G.G..B.B..G.BXBX.BHBHBH',
  'H..BBB.XB.B.B.BBXB..G.BHBHBH',
  'H..G.G.G..B.B.B..G.BBHBHBHBH',
  'H.BX.XBB..B.B.B.BBBBBHBHBHBH',
  'H..G.G.G..B.B.B.B...BHBHBHBH',
  'H..BBX.XB.B.B.B.B.G.BHBHBHBH',
  'H........EB.B.B.BBBBBHBHBHBH',
  'BBBBBBBBBBB..........H.H.H.H',
]

const LEVEL_61: LevelDef = [
  '..........T.................',
  '..........T.................',
  '.G.E.G...SHS...--------.P...',
  'HSBBBSSB.SHG..........BBBB..',
  'HS.......SHS....G..........G',
  'HS----...SHS..BBBB---......H',
  'HS......GSHS..G.........G..H',
  'H..GSBBBSSHSBBB......HBBBB.H',
  'HSBSS....SHS......EG.HB....H',
  'HS-------GHS...BBBBBBBB....H',
  'HS....G..SHS...G........G..H',
  'HS...SBBBSHS--BBBB--..HBB..H',
  'HSG......SHS........G.H....H',
  'HSBB.....SHS......BBBBB....H',
  'H.....E...H................H',
  'SBBBSBBBBSSSSBBBSBBBBSSBBSSS',
]

const LEVEL_62: LevelDef = [
  'BBTBBBBTBBBBBTBBBBBTBBBBBTBB',
  'B.TGE..T.....T...G.T.G...T.B',
  'BHBBBBBBBBXBBBBXBBBBBBBBBBHB',
  'BHBG.......EG........G...BHB',
  'BHBBBBBXBBBBBBBBXBBBBBBBHBHB',
  'BHB..G..........G......BHBHB',
  'BHBHBBBBXBBBBXBBBBBXBBHBHBHB',
  'BHBHB................BHBHBHB',
  'BHBHBHBG.....E.....G.BHBHBHB',
  'BHBHBHBBBXBBXBBBXBBBBBHBHBHB',
  'BHBHBH...G........G...HBHBHB',
  'BHBHBBBXBBBBBBBBBBBBXBBBHBHB',
  'BHBH...G.........G......HBHB',
  'BHBBBXBBBBXBBBBXBBBBBBXBBBHB',
  'BH...E...G....P.....G..E..HB',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_63: LevelDef = [
  '..................E.........',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBT',
  'G.E.....B.......G..B.G.....T',
  'BBBHB.BHBHBBBBBBBB.BHB.BBHBB',
  'BBBHBHBHBHB..G...B.BHB.BBHBB',
  'BBBHBHB.BHB.BBBB.B.BHB...H.H',
  'BGBHBHBHBHBHBP.B.B.BHB.BBBBH',
  'B..HBHBHBHBHBB.B.B.BHB.BH..H',
  '.HBHBHBHBHBH..GB.B.BHB.BHBBB',
  'HBBB.HBHBHBBBBBB.B.BHB.BH..H',
  'HBB.BHBHBH.G.....B.BH.-BBBBH',
  'H..-BHBHBBBBBBBBBB.BHB.BH..H',
  'HBB.BHBH...........BHB.BHBBB',
  '--B.BHBBBBBBBBBBBBBBHB.BH..H',
  '.....H......E.......HB.BBBBH',
  'BBBBBBBBBBBBBBBBBBBBBB.E...H',
]

const LEVEL_64: LevelDef = [
  'ST........................TS',
  'ST..EGGGGGGGG.GGGGGGGGGE..TS',
  'SSSSSSSSSSSSSTSSSSSSSSSSSSSS',
  '......G.G....T.....G..G.....',
  '....SHSSSS...T...SHSSSSS....',
  '.....HG.G....T....HG..G.....',
  '...SSSSSSHS..T..SSSSSSSHS...',
  '......G.GH...T.....G..GH....',
  '..SHSSSSSSSS.T.SHSSSSSSSSS..',
  '...H..G.G....T..H..G..G.....',
  '.SSSSSSSSSSHSTSSSSSSSSSSSHS.',
  '......G..G.H.T....G...G..H..',
  '.SHSSSSSSSSSSTSSSSSSSSSSSSS.',
  '..H.........................',
  '..H...G..G......P.G...G....E',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_65: LevelDef = [
  '...................BBBBBBB..',
  '----------G......ET.BBBBBB..',
  'H........HBH----...T.BBBBBBH',
  'H.......HXBXH.GHG...T.BB..BH',
  'H-------HXBXH.BBBH...T.BG.BH',
  'H.......HXBXHEBBBH....T.BBBH',
  'HE......HHHHH.BBBH.....T.BBH',
  'B-----..SXHXS.BBBH......T.BH',
  'BBG..H..SXHXS....H.......TTH',
  'BBBG.H..SXHXS.H--H---------H',
  'BBBBGH..SXHXS.H.............',
  'BBBBBHE.SXHXS.H------HBBGBBB',
  '.....H..SXHXS.H.....HSBBBBBB',
  '.....H..SXHXS.H....HSBBBBBBB',
  '.....H...PH...H....HSBBBBBBB',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_66: LevelDef = [
  'BBBBBBBHH----------HHBBBBBBB',
  'BBBBBBHH...-....-...HHBBBBBB',
  'BBBBBHH.....BEEB.....HHBBBBB',
  'BBBBHH....-.BBBB.-....HHBBBB',
  'BBBHH....-.BBBBBB.-....HHBBB',
  'BBHH-----.BBBBBBBB.-----HHBB',
  'BHH....-.BBBBGGBBBB.-....HHB',
  'HH......BBBBBBBBBBBB......HH',
  'BHH....-.BBBBGGBBBB.-....HHB',
  'BBHH....-.BBBBBBBB.-....HHBB',
  'BBBHH....-.BBBBBB.-....HHBBB',
  'BBBBHH....-.BBBB.-....HHBBBB',
  'BBBBBHH....-....-....HHBBBBB',
  'BBBBBBHH............HHBBBBBB',
  'BBBBBBBHHE...P....EHHBBBBBBB',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_67: LevelDef = [
  'T...........................',
  'T....B...E.B.......E...E....',
  'T------GHBH.BBHBBTTBTTBBH...',
  'H......BH.BHB.HB.GB.GB..H...',
  'H.P.....B..B.HB.HB..B...H...',
  'BBBBB....BB.HB..B..B....H...',
  '....B...GB.HB.GB..B.---.H...',
  '...B....B.HHH.B....B..BBBBBH',
  '.GB...GB..BHHB..BB..X......H',
  'BB....B.GB.HB..B..B..B.....H',
  'B...GB..B.HB..B....B..BG...H',
  '....B.GB.HB.GB..HB..BG.B...H',
  '..GB..B.HB..B...H.B..B..B..H',
  '..B.GB.HB..B....H..BG.B..B.H',
  '.B..B.HH.....G..H...B.....BH',
  '......HBBBBBBBBBBBBBBBBBB..H',
]

const LEVEL_68: LevelDef = [
  'SSSSSSSSSSSSSSSSSSSSSST....S',
  'S.........E...........T....S',
  'S....HBSBBSSBHS.......T....S',
  'S....H......THSBSBBSSBT....S',
  'S.BBSH.....HTHB.B.EB-------S',
  'SG...H...GTHTBB.B.SB......GS',
  'S....H...HTHTB..B..B......ES',
  'SH...H...HTHTB.GBP.B......BS',
  'SH...H...HTSBB..BB.B.....GBS',
  'SHSSSSXBSSTS.....B.B.....BBS',
  'SH.--------S-----B.B..G...BS',
  'SH.....G..H.....BB.B....BBBS',
  'SH..HSXSSSHSSSBHB..B...GB..S',
  'SH..HS...SHS..BHBBBBXBSB.G.S',
  'SH..HS...SHSG.BH........BBSS',
  'SH.GHS.E.SHSBBBBBSSBBBSBBBBS',
]

const LEVEL_69: LevelDef = [
  'H.E.BB..........------------',
  'HBBBBB.......BBH............',
  'HBBBBB.......BBH.BSBSBSBSBSB',
  'HBBBBB.......BBH.G.G.G.G.G.G',
  'HBBGBB.......BBHBXBXBXBXBXBX',
  'HBBBBB.G..E..BBHBXBXBXBXBXBX',
  'HBBBBBBBBBBBBBBH------------',
  'HBBBBBBBBBBBBBBH...S.S.S.S.S',
  'H..P.E.........H...BXBXBXBBB',
  'HBBBBBBBBHBBBBBBBBH.....XBBB',
  'HBBBBBBBBH...BBBBBHBBBBHXBBB',
  'HBBBBBBBBHBBG..BBBHBBBBHXBBB',
  'HBBBBBBBBHBBBBG..BH.E..HXBBB',
  '.........HBBBBBB..HBBBBHXBBB',
  '....G.G..HBBBBBBBBHBBBBHXBBB',
  'BBBBBBBBBBBBBBBBBBH.GG.HXBBB',
]

const LEVEL_70: LevelDef = [
  '...........................T',
  '...........................T',
  '.....................E-GGG-T',
  '..G-G-...............HGBBBGH',
  'GHB.B.G-............GHBBBBBH',
  'BH....B...........G.BHBBGBBH',
  '.H......G-........BH-HBBBBBH',
  '.H......B.......G.-H..GBBBG.',
  '.H..............BH..........',
  '.H........G......H....GGGG..',
  '.H........B...G.-H...GBBBBG.',
  '.H............BH.....BBBBHX.',
  '.H.........G-..H.....BBBHXB.',
  '.H.........B.G-H.....BBHXBB.',
  '.H..........GB.H.....BHXBBB.',
  '.H..P.......B..H.E...HXBBBB.',
]

const LEVEL_71: LevelDef = [
  '....T.......................',
  '....T..............E........',
  '....T............HBBBBBH....',
  '.GHBBBBHBHE....G.HB...BH....',
  'BHBBBBBHBBBBBHBBHBBBBBBHBBBH',
  'BH....SH.G..SH.SH..SB.BH..GH',
  'BH.BBBSH.SB.SH.SH.GSB.BH.BBH',
  'BH.GBBSH...GSH.SH.B.B.BH.BBH',
  'BH.BBBSH.B.BSH.SH.SS..BH.BBH',
  'BH...GSH.S...HGBH.BBG.BHE.GH',
  'BHBBBBBHBBBBBHXBHBBBBBBHBBBH',
  'GH-------.GG.H..E.BB.....SGH',
  'SSSH....BBSSSBBHSSBG.....GSH',
  '...HBBBGBSSSSSBHSSSSSSHSSSSH',
  'P..HBGBBGGGGGG.HG.....H....H',
  'SSSSSSBBBBSSSSSSSBBBBBBBBBBB',
]

const LEVEL_72: LevelDef = [
  'T...........................',
  'T......------------------BBB',
  'H....GE.........H..........B',
  'HBBXBBBB........H..........B',
  'H......B........H.GEH.BB.G.B',
  'H.G.H..B.G...---HBBBHBBBBBBB',
  'HBBBHG.BBBBB.G..H...H.......',
  '....HBBBBBBBBBBXH...H......G',
  'H...HBB..G.BBBBXH.GBH-----BB',
  'HBBBHBBBBBBBBBBXHBBBH.G.H.BB',
  'H.....B---------HBGBHXBBH.BB',
  'HGEH..B.....G...HBBBH...H.BB',
  'BBBH..B...G.BB..HBBBH...H.BB',
  '...H..B.G.BB....HBBBH...H.BB',
  '...H.PBBBB....G.HBBBH..EH.BB',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_73: LevelDef = [
  '............................',
  '......TTTTTTTPT.......T.....',
  '....E....T....TT.....TTES...',
  '..GHG....T.....TT...TT.SSS..',
  '.GHHHG...T......TT.TT.SSSSS.',
  'GHHHHHG..T.......TTT.SSSSSSS',
  'HHHHHHH--T..GE.G..T----HHH..',
  '...H....BBBBBBBBBBBB....H...',
  '..GSG...B.G......G.B....H...',
  '.GSSSG..B.--------.B....H...',
  '.SSSSS..B.H......H.B....H...',
  '..SSS...B.H......H.B....H...',
  'HBBBBBH.BGH...E..HGB....H...',
  'H.....H.BBBBBBBBBBBB....H...',
  'H.....H..H........H.....H...',
  'HBBBBBHHBBBBBBBBBBBBHHBBBBBH',
]

const LEVEL_74: LevelDef = [
  '.....T......................',
  '.....T...........SSSSSSSSSSS',
  'SSSSSTSSSSSH----H..........S',
  'S....T.....H.P..H...E......S',
  'BBBBBHBBBBBBBBBBBBBBBBBBBBBB',
  'BBH..H..HBBB....BBBB......BB',
  'BHHBBBBBHBBB.BB.BBBBBBBBBBBB',
  'BHBBBBBB.HBB.GB.BBB.BB..BB.B',
  'BHB.BBB.BHBB.BB.BBB.GBBB.G.B',
  'BHBB.G.BBHBB....BBB.BB.GBB.B',
  'BHBBBBBBBHBBBBBBBBBXBBBBBBBB',
  'BH..B.BG.HH..............EHB',
  'BHBBBBBBB.HBBBBBBBBHBBBBBBHB',
  'BH.GBBB...H......BBH......HB',
  'BH......E.H...G..BBH...G..HB',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_75: LevelDef = [
  '.........G...G..............',
  '.G...G...BBHBB...G...G....G.',
  '.BBHBB.....H.....BBHBB...BHB',
  '...H......H........H......H.',
  '....H......H........H....H..',
  '...H.......EH...GG...H....H.',
  '..H........H....BB..H.----.H',
  '...H......H........H......H.',
  '....H......H.------.H....HP.',
  '...H.-----.EH........H....BB',
  '..H...GG...H........H.......',
  '...H..BB..H........H........',
  '..E.H......H........H.E.....',
  'BBBBBXXXXXXXXXXXXXXXBBBBBBBH',
  '...........................H',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_76: LevelDef = [
  'BBBBBBBBBBBBBBB............T',
  'B.............B............T',
  'B.------------HHBBBBBBBG...T',
  'B.............HB..G..B.B---H',
  'BG.GE......P..HB.....B.BE..H',
  'BHBBBBBBHSSSSSSBSS...H..BB.H',
  'BH.....BH......BBB...H.....H',
  'BHG....BH-------...E.BH....H',
  'BH...BBSH......BBBBBBBH...HB',
  'BH..BBGSH....BBB.....BHBBBBB',
  'BH..B..SH..GBBGB.GG..BHBB.BB',
  'BHBB...SH..BB..BBBBBBBHB.B.B',
  'BHBG...SH.BB...B-----BHBB.BB',
  'BH.....HHHB....B..G..BHBGB.B',
  'BH.....HBH...........BHBB.BB',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_77: LevelDef = [
  '.----......GGGGGGG.....----.',
  'H....BBBBBBBBBBBBBBBBBB....H',
  'H.SSSBBBBBBBBBBBBBBBBBBSSS.H',
  'H....BBBBBBBBBBBBBBBBBB....H',
  'HESH.BBBBBBBBBBBBBBBBBB.HSEH',
  'SSSH.B....B....B....BBB.HSSS',
  '...H.BGGGGBGGGGBGGGGBBB.H...',
  '...H.BBBBBBBBBBBBBBBBBB.H...',
  '...H.BBBBBBBBBBBBBBBBBB.H...',
  '...H.BBBBBBBBBBBBBBBBBB.H...',
  '...H.BBB....B....B....B.H...',
  '...H.BBBGGGGBGGGGBGGGGB.H...',
  '...H.BBBBBBBBBBBBBBBBBB.H...',
  '...H.BBBBBBBBBBBBBBBBBB.H...',
  '...H.BBBBBBBBBBBBBBBBBB.H...',
  '...H...................PH...',
]

const LEVEL_78: LevelDef = [
  'B.........................BT',
  'B......G..E...-----------GBT',
  'BBBBBBBBBBBBBHH....E.G..HBBT',
  'BBBB.........HHBBBBBBBBBBB.T',
  'BBBBB..G..E..HH........BB..T',
  'BBBBBBBBBBBBBHH..G....BBBH.T',
  'BBBBBBB......HHBBBBBBBB..H.T',
  '...G..BB..G..HH.....BBBXBH.T',
  'HBBBBBBBBBBBBHH.G..BB....H.T',
  'HBB.B.BBBB...HHBBBBB.G...H.T',
  'H..HBHB.GBB..HH..BBBBBXBBH.T',
  'SSSH.HBHBBBBPHH.BB.G.....H.T',
  'SSSSSH.HB.BBBHHBBBBBXBBBBH.T',
  'SSSSSSSHHHB.BHHB.........H.T',
  '.........H.H.HH..........H.T',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_79: LevelDef = [
  '.....................T......',
  '....E...........S....T...E.G',
  'HSSSSS.SSSSSSSHSS...BTBHBBBB',
  'H.......---...HSGBBHBTBHBBBB',
  'BBHBB.BB..HBE.H.BBBHBTBHBBGB',
  '..H..BBGB.H.B.HBB..HBTBHBBBB',
  'HB...BBBBXH..BH..HBBBTBH....',
  'H....P....H...B..HB..T.BBBBH',
  'HBBBBBBBB.B.GB..GHBHBBBBBBBH',
  'HBBBBBBBBXB.B..BBBBHBB.....H',
  'HBBBBBBBBXB.....GBBH..BBBBBB',
  'HBBG...BBXB----HB.BH------..',
  'HBB...GBBXBH...B..BG....B.BH',
  'HBBBBBBBBXBH..BBBBBBBHBBBGBH',
  'H...BBG....H.BB......H..BBBH',
  'HBBBBBBBBBBHBBBBBBBBBBB....H',
]

const LEVEL_80: LevelDef = [
  '......-----------G..........',
  'SSSSSS...BB.....BSSSSSSBH...',
  'S------..GG.....B......BH...',
  'SH......BBBX....B.E...GBH...',
  'SHGG....G..G....BBBBBBXBH...',
  'SSSSH.G.BXBB..........EHH...',
  '....H.......G...G...E--.H...',
  '....H.....BSSSSSSSSSB--.H...',
  '....HGE.G.BE.....G..B...H...',
  '....HBBBBHBBBBBBXBBBB...H...',
  '.....B..BH..............H...',
  '.....B..BH..............H...',
  '.....BGGBH..............H...',
  '.....BBXBH..............H...',
  '.........H....E..P......H...',
  'BBBSSSSSBBBSSSSBBBSSSSBBBSSS',
]

const LEVEL_81: LevelDef = [
  'T...........................',
  'T...........................',
  'SSSSSSSH...............HSSSS',
  '.......H...E.........E.H....',
  '.......HBBBBBBBSSSBBBBBH....',
  '...B...H...............H....',
  '..B..--H...............H....',
  '..B.G.GH....GBG.....GGGH....',
  '..B.BGBH--..B.B.GGG.BBBH--..',
  '.B..BGBHG.G--GB.BBB.BGBHG.G-',
  '.B..BBBHBGB.GBG.GGG.BBBHBGB.',
  '.B....BHGBG.BBB.BBB.BGBHGBG.',
  'B.....BHBGB.........BBBHBGB.',
  '.......H-H.............H-H..',
  '.......H....P..........H....',
  'BBBSSSBBBBBBBBBSSSSBBBBBBBBB',
]

const LEVEL_82: LevelDef = [
  'SSSSSSSSSSSS.T.SSSSSSSSSSSSS',
  'S--------HBS-T-SBH---------S',
  'S......G.HB--T--BH.G.......S',
  'S...G..BBH--GTG--HBB..G....S',
  'S..GBBX-HHBSBTBSBHH-BXB.G..S',
  'S.GBB--H-BX-HTH-XB-H--BBBG.S',
  'BGBB--H-----HTH-----H---BBGS',
  'BX---H------HTH------H----XB',
  'B---HE------HTH------EH----B',
  'B...HBBBBBBXHPHXBBBBBBH....B',
  'B.G.H.......BBB.......H..G.B',
  'H...H....E..BGB..E....H....H',
  'H---HBXBBBBBH.HBBBBBXBH----H',
  'H.G..H......H.H......H..G..H',
  'H....H..G...H.H..G...H.....H',
  'BBBBBBBBBSBBBBBBBSBBBBBBSSSS',
]

const LEVEL_83: LevelDef = [
  '.----G................G.GPBT',
  '.....BH..............HBBBBBT',
  '.....BH.............HXBBBBBT',
  '.....BH............HBXBB..BT',
  '.....BH...........HBBXBBG.BT',
  '.G.E.BH..........HBGBXBBXXBT',
  'BBBB..BH........HB.HBXBB..BT',
  'G...BG.BHG.....HB.GHBXBB..BT',
  'BBBH.B..BBH...HBBBBHBXBB..BT',
  'G..BH.BG.BHGEHB.G.GHBXBB..BT',
  'BBH.BH.B..BBHBBBBBBHBXBB..BT',
  'G.BH.BH.BG.BH.G.G.-HBXBB..BT',
  'BH.BH.BH.B.BHBBBBB.HBXBBXXBT',
  '.BH.BH.BH..........HBXBB...T',
  '..H..H..H.....E....H.......T',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_84: LevelDef = [
  '......................T.....',
  '......................T.....',
  'E.......GBG...........TBG...',
  'BBBBBHBBBBBBBBHBHBBBBBBBBBBH',
  'G...BH.G......HBH....B.....H',
  'BBBHBBBBBHBBBBBBBBBBHBHBBBBB',
  'G..H.....H..E.......HBH....G',
  'BHBBBBBBBBBBBBBBHBBBBBBBBBBB',
  'GHBBG..B......GBH....E.BG...',
  'BBBBBBBBBHBBBBBBBBBHBBBBBBBB',
  'BBH.....EHBBBG.BB..H..BB..GB',
  'BBHBBBBHBBBBBBBBBHBBBHBBBBBB',
  'G.HBBBBHB.GBBBBBGHBBBH....BB',
  'BBHBBBBHBBBBBBBBBHBBBBBBHBBB',
  'BBH...BH.....B.P.H..B...H..G',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_85: LevelDef = [
  '..............E..G..........',
  '.........G..BBBBBBHB.G......',
  '.....BBBXBBBB.....HBBBBBXB..',
  '.....B......B.....HB.....B..',
  '.....B.EG...B.....HB.....B..',
  '.BBBBBBBB.G.BG..BHBBBBBGGB..',
  '.B......BBBXBBBBBH....BXBBBB',
  '.B......B.....G.BH.EG....-.B',
  '.B......B....HBBBBBBBBBBB.HB',
  '.B...G.GB....HB.........G.HB',
  '.B..BBBBB....HB.G..HBH.HBBBB',
  '.BBBB...B.GBHBBBB..HBBBXB...',
  '....B.G.BBBBH...B.GHB.......',
  '....BBBBB..BH...BBBXB.......',
  '............H......P........',
  'SBSBSBSBSBSBSBSBSBSBSBSBSBSB',
]

const LEVEL_86: LevelDef = [
  'T..........................T',
  'T--------------------------T',
  'HH........................HH',
  'H..BXBB....BBBXBB..BBBBBB..H',
  'H..B..BB...B....B..B....X..H',
  'H..B...BB..B.......B.......H',
  'H..B....B..B.......B.......H',
  'H..B...GB..B....G..B.......H',
  'H..B...BB..B...BB..B....G..H',
  'H..BG.BB...B...GB..BG..GB..H',
  'H..BBBB....BBBXBB..BBXBBB..H',
  'H......P...................H',
  'H.HBBBBBB..BBBBBB..BHBBBB..H',
  'H.HB...GB..BBBBBBH.BHBBGB..H',
  'HEHB....B.EBB.GBBH..HBBBB..H',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_87: LevelDef = [
  '.T..........................',
  '..T.........................',
  '.HG....GH......GH.....GH....',
  '.GH....HG......HG.....HG....',
  '.HG....GH......GH.....GH....',
  '.GH....HG......HG.....HG....',
  '.HG....GH......GH.....GH....',
  '.GH....HG......HG.....HG....',
  '.HG....GH......GH.....GH....',
  '.GH....HG......HG.....HG....',
  '.HG....GH......GH.....GH....',
  '.GH....HG......HG.....HG....',
  '.HG....GH......GH.....GH....',
  '.GH....HG......HG.....HG....',
  'PHG....GH.....EGH...E.GH..E.',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_88: LevelDef = [
  '.--------B..........E.......',
  'H........B..G....HBBBBH.B.BH',
  'H.XXXXXX.BBBBBHS.HS...H.B.BH',
  'H.XXXXXX.B..G.HS.HSHS.H.B.BH',
  'H.XXXXXX.BHBBBBS.HSHS.H.B.BH',
  'H.XXGGXX.BH.G..S.HSHS.H.B.BH',
  'H.XXXXXX.BBBBBHS.HSHS.H.B.BH',
  'H.XXXXXX.B..G.HS.HSHS.H.BGBH',
  'H.......EBHBBBBS.HSHS.H.BBXH',
  'HBBBBBBBBBH.G..S.HSHS.H....H',
  'HBBBBBBBBBBBBBHSBBSHSBBBBBBH',
  'HBBBBBBBBB..G.HSSSSHSSSSBBBH',
  'HBBGGBBBBBHBBBBS.G.T.G.SGBBH',
  'HBBBBBBBBGHSBSSSSSSSSSSSBBBH',
  'HSSSSSSSSSS.......G..EG....H',
  'H.P........HBBBBBBBBBBBBBBBB',
]

const LEVEL_89: LevelDef = [
  'STBSSSBSSBBSBBSSBS.SSBSSBBSB',
  'SHTTTTTSTSBSSBTSTTTTTTSSBBBB',
  'SH.P.GTST.GGG.T.T..E.T.G..TB',
  'SHSBSBTSTBSBBSHBHSBBBHBBBBTB',
  'SH.G..TST.GGG.H.H.GBBHBBBSTB',
  'SHSBSTTST.BBB.H.H.SSGHGBBGTB',
  'SHTTT.GST.....HGH..BSHSBSSTB',
  'SH..TBBST..G..HSH..G.H----TB',
  'SHG.ET.ST.BBB.HSH..BSH..GSBB',
  'SHBBBBHST..B..HGH..B.H.BBGTB',
  'SH..S.HSTTTTTTHSH..B.H...SHS',
  'SH..S.H---------HGEB.HSGGGHB',
  'SH..SGHSBBBBH.GSHBBBBBBBBBBB',
  'SH..SBHS...BBBBBSBS-------HB',
  'SH.G..H..G...G.......E.GGGHB',
  'SBBBBBBSBSSSSSSSSSSSSBSSSSHB',
]

const LEVEL_90: LevelDef = [
  '..................H...T.....',
  '........--........H...T.....',
  'G...G..--.H.....--H..GTE....',
  'BBBBH--...H.E..---BXBBHBH...',
  '....H..SBXBH..---GBG..TBH...',
  'XXBBBH..G..H-HSS.SBBBBBBH...',
  'XG...H..S....H...SSSS.--H...',
  '.XG..H......GH.G.....HS.....',
  '..BG.HBXBBHSSSSSSHBXSHS.....',
  '..HBGH....H..G...H...HS.....',
  '..H.XHS...HBXBBBBHBBSHS.....',
  '..H.-H..G.H..G...H..SHS.....',
  '..HS.G..S.HBBBBXBH.SGHGS....',
  '..H..S....H..G...H.SSHSS....',
  '..H.......HBBXBBBH..EH......',
  'BBBBBBBBBBH..E..PHBBBBBBBBBB',
]

const LEVEL_91: LevelDef = [
  '..............T.............',
  '..............T.............',
  '..............T.............',
  '.------...E..HBH..E...------',
  '......H---HBGHBHGBH---H.....',
  '.HBG.BH...HBBBBBBBH...HB.GBH',
  '.HBBBB....H-HB.BH-H....BBBBH',
  '.HHBB.......HBBBH.......BBHH',
  '..HBB.......HB.BH.......BBH.',
  '..HBB.......HBBBH.......BBH.',
  '..HBB.......HB.BH.......BBH.',
  '..HBB.......HBBBH.......BBH.',
  '..HBB.......HB.BH.P...E.BBH.',
  '..HBBBBBBBBBHBBBHBBBBBBBBBH.',
  'G.HBB...G..BH.G.HB..G...BBHG',
  'SSSSSSSSSSSSSSSSSSSSSSSSSSSS',
]

const LEVEL_92: LevelDef = [
  '........................T...',
  '...............G.....BEBTB..',
  '......H---HBBBBBBBBBBB.BTB..',
  'G.----H....B......G..B.BTB..',
  'BH.........B....BBBBBB.BTB..',
  'BBH......E.B....G......BTB..',
  'BBBH.....G.B.....-----.BTB..',
  'BBBBH.-----BG..GB....H..T...',
  'SSSSSSH....BBBBBB....H--T...',
  '......H....BBBBBB....H.BBBBB',
  '......H....BBBBBB....H.BG.E.',
  '......H....BBBBBB....H.BBBBH',
  '......H..............H.....H',
  '....--H..............H.....H',
  'E.GB..H.......P......H.....H',
  'BBBB..HBBGBBBBBBBBBBBH..BBBH',
]

const LEVEL_93: LevelDef = [
  '.............TT.............',
  '..E.HHHHH..GGTTGG..HHHHH.E..',
  '....HHHHH.HBBBBBBH.HHH.H....',
  '..HBH.H.H.H..G...H.H.H.HBH..',
  '..HBH.H.H.HBBBBBBH.H.H.HBH..',
  '...BH.H.H-H..P.G.H-H.H.HB...',
  '...GS.H.S-BBBBBBBB-S.H.SG...',
  '...XH.H.H-HBBBBBBH-H.H.HX...',
  '..HXH.H.H-HBBBBBBH-H.H.HXH..',
  '..HHH.H.H..HBXXBH..H.H.HHH..',
  '..HHH.H.H..HBXXBH..H.H.HHH..',
  '...HH.H.H...BGGB...H.H.HH...',
  '....HHH.H..........H.HHH....',
  '.....HHHH..........HHHH.....',
  '......HHH..........HHH......',
  '.......EHBBBBBBBBBBHE.......',
]

const LEVEL_94: LevelDef = [
  'G..BBBBBBBBBBBBTBBBBBBBBBBBB',
  'HB---....-...GBTB..........B',
  'HBGB.BBBB.BBBBBTBHBBBHBBBBHB',
  'HBGB.B..B...G.BTBHBBBHBBBBHB',
  'HBGB.BGGBBBBBBBTBH..BH.EGBHB',
  'HBGB.BBBBBBBBBBTBBBHBHBBBBHB',
  'HBGB..G....E...T..BHBHBBBBHB',
  'HBGBBBBBHBBBBG.T.GBHBH....HB',
  'HBGB....H...BBBBBBBHBBBBBBHB',
  'HBGBHBBBGBBH..G...BH...G.BHB',
  'HBGBHB.G..BBBBBBBHBBBBBBBBHB',
  'HBGBH.HBBHEG....BH....G..BHB',
  'HBGBBBBBBBBBBBBHBBBBBBBBHBHB',
  'HBGBG..B.G.B.G.HG.B...G.HBHB',
  'HBXBHBHBHBHBHBBBBBBHBBBBBBHB',
  'H.G.HBHGHBHGHBP..G.H..G...HB',
]

const LEVEL_95: LevelDef = [
  '..T.........................',
  '..T.........................',
  '..T......-----........-----H',
  '.EH....-......H..--.EH.....H',
  'XBH---H.BXBB..HBB..BBH.BBXBB',
  'XB....HBBXBBB.HBB..BBH.BBXB.',
  'XB....HBBE-...HBB..BBH.BB...',
  'XB....HBBH.BB.HBB..BBH-.B...',
  'XB.G..HBBHGBB.HBBG.BBGHXXGP.',
  'X.--H-HBBH.BB.HBB..BB.HBBBB.',
  'BB.HH..BBH..B.HBB..BB.HBBBB.',
  'BBHH...BBH.X.-HBB..BB.HBB...',
  'BBH....BBH.BB..BB..BB.HBB...',
  'BBH.G--BBH..G...B.GB..H...G.',
  'BBBBBH.BBBBBBH..BBXB..HBBBBH',
  'BBBBBH.GBBBB.H..GBXG..HBBBBB',
]

const LEVEL_96: LevelDef = [
  '.-..E...BBBB.E..G...BBBB....',
  'H.HBBBBHBBBBHBBBBBB.BBBBBBBH',
  'H.HBBBBH..G.HBBBGBB.BBBBGBBH',
  'H.HBGGBHBBBBBBBBBBB....BBBBH',
  'H.BBBBBH.....--------------H',
  'H.....BHE........G..G.......',
  'HBXBH.BHBBBBBXBBBBBBBH.G.G..',
  'HG.BH.BH-----.-----HSSSSSSSS',
  'BB.BH.BH....G.G....H..PG..G.',
  '...GH.BHBBBBBXBBBBBHBBBBBBBH',
  'BBHSS.BH-----------H.......H',
  'BBH...GH....G.....SBBBBBBH.H',
  'BBHBBBBBBBBBBBBBBTS....G.H.H',
  'GBHB.............TSBBBBBXB.H',
  'BBHB.....G....G..TS....E...H',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_97: LevelDef = [
  '.............HH----HHHHHBBBB',
  '............HBBH---HGG.HBBBB',
  '...........HBBBBH...HHGH.H.H',
  '..........HBBBBBBH....HHGHGH',
  '..........HBBBBBBH.....HHHHH',
  '..........HBSBSXSH.....H.H.H',
  '..........HGSBSXGH.....H.H.H',
  '..........HBSBSXSH.....HGHGH',
  'G---------HBSBSXSH.....HHHHH',
  'HG........HGSBSXGH.....H.H.H',
  'BHG.......HBSBSXSH.....H.H.H',
  'BBHG......HBSBSXSH.....HGHGH',
  'BBBHG.....HGBBBXGH.....HHHHH',
  'BBBBHG....HBBBBBBH.....H.H.H',
  'BBBBBHG..HSB.BS.BSH...PHGHGH',
  'BBBBBBH.EHSB.BS.BSHE.HBBBBBB',
]

const LEVEL_98: LevelDef = [
  'ST.........................S',
  'STSSSS.SSSSSSSSSBSSSSSSSSSGS',
  'ST....G...G----...--------HS',
  'ST.......HBB..BBBBB.....BBHS',
  'ST.....G.H.......GB..B.GBGHS',
  'ST....BBBH..G.P..BB..BXBBSHS',
  'ST.G.....HBBBBBH..B.E.....HS',
  'ST.BBB...HB...BH..B---HBBBBS',
  'ST.....E.HBG..BH..B...H---.S',
  'ST...HBBBBBBBBBHBBB...H..G.S',
  'SBBB.HBG.B.G..B...B...H.BBBS',
  'SG.BBHBBBBBBBBB...B...H.B..S',
  'SBBBBH---GGSGGBG..BBSSSHSBBS',
  'S...BH..BBBSBBBBBHB....H..GS',
  'S.G.BH....G......HH..E.HBH.S',
  'BBBBBHBBBBBBBBBBBBHBBBBBBBBB',
]

const LEVEL_99: LevelDef = [
  '..---......G..G....---..S.BH',
  'BB..BH....HBBBBH..HE..BBS..H',
  '.BB.BH...HBBBBBBBBBBH.BBS.BH',
  'BB..BHBBBBBGBBGBBBBBH.BGSBBH',
  'GBBGBH.....E........H.....BH',
  'BBBBBBBBBBBBBBBBBXBBBBBBBBBH',
  '...G.E...G..........P...E..H',
  'SSSSSSSSSSSSSSSSHBBBBBBBBBBB',
  '.-------------.SH...........',
  'H......-......HSH----------.',
  'H.....-.-.....HSBB.BB.BB.BBH',
  'H....-.B.-....HSSSSSSSSSSSSH',
  'H...-.BBB.-...H------------H',
  'H..-.BBBBB.-..HXBXBXBXBXBXBX',
  'H.-.BBGGGBB.-.HS............',
  'H-.BBBBBBBBB.-HS........E...',
]

const LEVEL_100: LevelDef = [
  '.................E.E.E-.....',
  '...............HBBBBBB.HBBBH',
  '...............HB....B.HBBBH',
  '...........HBBBBBB...B.HBBBH',
  '...........HB....B...B.HBBBH',
  '.......HBBBBBB...BGGGB.HBBBH',
  '.......HB....B...BBBBB.HBBBH',
  '...HBBBBBB...BGGGB.....HBBBH',
  '..EHB....B...BBBBB.HBBBBBBBH',
  'BBBBBB...BGGGB....EHB....BBH',
  'B....B...BBBBB.HBBBBBB...BBH',
  'B....BGGGB.....HB....B...BBH',
  'B....BBBBB.HBBBBB.GGGBGGGBBH',
  'BGGGGB.....HBSSSSSSBSSSBSSSH',
  'BBBBBB.HBBBBB........P.....H',
  '.......HBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_101: LevelDef = [
  'H..........................H',
  'H.....HBGBBH.....HBBGBH....H',
  'HEG...HBBBBH.....HBBBBH...GH',
  'BBBBH.HBBBBH-----HBBBBH.HBBB',
  '....H.HBBGBH.....HBGBBH.H...',
  '..GEH.HBBBBH.....HBBBBH.HG..',
  'HBBBB.HBBBBH.....HBBBBH.BBBH',
  'H.....HBGBBH-----HGBBBH....H',
  'H.G...HBBBBH.....HBGBBH..G.H',
  'BBBBH.HBBGBH.....HBBBBH.HBBB',
  '....H.HGBBBH.....HBBGBH.H...',
  '..G.H.HBBBBH-----HBBBBH.H.G.',
  'HBBBB.HBGBBH.....HBBBGH.BBBH',
  'H.....HBBBBH.....HBGBBH....H',
  'H..P..HBBGGH..E..HBBBBH..E.H',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_102: LevelDef = [
  '---------....H......-----...',
  '.........H....H....H........',
  '...------H.G...H...H........',
  '..H.G.E..BBB...H....H.......',
  '..H.BBBB......H.---..H.GG--.',
  '..H..........H...G...H.SS...',
  '..H----...G.H....S..H......G',
  '.......H.BB.H......H.......B',
  '.......H.....H.....SSSBBBSBB',
  '.......H......H.--..........',
  '...GEG.H.......H.........S.S',
  '..BBBB.H----...H...SSSSSSS.S',
  'G........GG...H.G......G.GES',
  'S........SS..H..B..BBBBBBBBB',
  '...........P.H..............',
  'BBBBBSSSBBBBBBBBBSSSBBBBBBBB',
]

const LEVEL_103: LevelDef = [
  '-----------------------H....',
  '..G....G.....G.....G...H....',
  'BBBB..BBBB..BBBX..BBXB.H....',
  '.....G....G......G.....H....',
  'B..BXBB..BBXB..XBBB..B.H....',
  '.G......G...G......G...H....',
  'BBBB..BBBB..BBBX..BBXB.H....',
  '....G.....G.....G......H....',
  'B..BBXB..BXBB..XBBB..B.H....',
  '..G.....G.....G....G...H....',
  'BBBB..BBBB..BBBX..BBXB.H....',
  'E....P...........E.....H...E',
  'BBBBBBBBBBBBBBBBBBBBBBBBTBBB',
  'BBBBBBBBBBBBBBBBBBBBBBBBTBBB',
  'BBBBBBBBBBBBBBBBBBBBBB..T..B',
  'BBBBBBBBBBBBBBBBBBBBBB.ETE.B',
]

const LEVEL_104: LevelDef = [
  '............E..............T',
  '....G.................G....T',
  '..HBBBH....BBHBB....HBBBH..T',
  '.HB.G.BHHBBHHHHHBBHHB.G.BH.T',
  'BHBBBBBHBBHHHHHHHBHBBBBBBHBT',
  '.....E...HHHHGHHHH.........T',
  'BBBBBBBBBHHHHHHHHHBBBBBBBBBT',
  '.BBGBB...BHHHHHHHB..BBGBB..T',
  '..BBB.....BHHHHHB....BBB...T',
  '...B.......BHHHB......B....T',
  '............BHB............T',
  '............BHB............T',
  '............BHB............T',
  '............BHB............T',
  '....E........H.....P.......T',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBT',
]

const LEVEL_105: LevelDef = [
  'BBBBSSBBBBBBBBBBBBBBBBBBBBBT',
  'B.G..S.....G..E....P......BT',
  'BHBH.SBXBHBBBBBBXBBBBBBBB.BT',
  'BHBBH.BXBHHBBG--------G...BT',
  'BH.BBH.XBBHHBBG...G..GBBH.BT',
  'BH..BBH.BBBHHBBG....GBB.HBHT',
  'BHH..BBH.BBHHHBBG..GBB..HHHT',
  'BHHHG.BHH.BHBHHBB..BB..BHHBT',
  'BHHHH..HBH.HBBHHBXBB..BHHHBT',
  'BGHHHHEHBBHHBBBHHXB..HHHGHBT',
  'BHHG..HH.BBH.BBBHX.GBHHHHBBT',
  'BBBHBBBBG.BBH.BBH..BHHHEHHBT',
  'BHHHHHHHH..BHH.HHEHHHG..HHBT',
  'BH.HH.G..H..HBHHHBHHBBBBBHBT',
  'BG.HBHBBBBH.....HHHG.....H.T',
  'BBBBBHHHHGHBBBBBHHBBBBBBBBBB',
]

const LEVEL_106: LevelDef = [
  'SSSSSSSSSSSST..SSS.......SBS',
  'BBBBBBBSBBSST..BBS.......BSB',
  '...G..BSBSBST..SBS.......B..',
  'HSBBBXB....ST.E.BS......GB.G',
  'HBBBB...----HBBSBSXBBBBBHS.H',
  'HB.GB.---SBSHB....XSBBBBHB.H',
  'HBBB---..SBSHB----XSBBBBHSBH',
  'HBB---......HS.....G.BBSHBBH',
  'HB--G...BBSBHB....XBBSSBHBBH',
  'H--.S-------H...-----.BBH.BH',
  '...SBE..G..SHXBBS.P.G...HBBH',
  'BBXBSBB.SBBSHXBBSSBSSBS....H',
  'BBXBS......SHX....E.G.SBBBBB',
  'BBXBS-------HXBB..BBBBS..G.B',
  'BB.....G...SH..........BBBBB',
  'BSBBBBSBBH..H..HBBBSBBBBBBBB',
]

const LEVEL_107: LevelDef = [
  '.----------..P...----------.',
  'H....----..BBBBBB..----....H',
  'H....---.BBBBBBBBBB.---....H',
  'H....--.BBBBBBBBBBBB.--....H',
  'H....-.BBBBBGGGGBBBBB.-....H',
  'H....-.BBBBBBBBBBBBBB.-....H',
  'H.....BBBBBBBBBBBBBBBB.....H',
  'H.....BBGGGGBBBBGGGGBB.....H',
  'H.....BBBBBBBBBBBBBBBB.....H',
  'H.....BBBBBBGGGGBBBBBB.....H',
  'H......BBBBBBBBBBBBBB......H',
  'H....-.BBBBBBBBBBBBBB.-....H',
  'H....-..BGGGGBBGGGGB..-....H',
  'H....--..BBBBBBBBBB..--....H',
  'HEGGG---G..BBBBBB..G---GGGEH',
  'BBBBBBBBBHGGGGGGGGHBBBBBBBBB',
]

const LEVEL_108: LevelDef = [
  'BBBBBBBBBBBB....BBBBBBSSBBBT',
  'B---------------------.BB.BT',
  'B.HBBBBBBBBBH..TB-----H----T',
  'P.HGSGGGG...H..TBG..GGH...GT',
  'BBHBBBBBSBBBH..TBBBHBBBXBHBT',
  'B.HHHHH.S..GH..TBG.H-----H.T',
  'BG..SGH..GGBH..TBS.H.SSS.HGT',
  'BBBBBBBXBBBBH..TBG.HE..GGHSH',
  'B..GSGG.S..BH..TBBBBBBHBBBBH',
  'B..SSSS.S..BH--HBG....H..GGT',
  'B.GGG.GGSG.BHGEHBSG...H.BBBH',
  'BHBBBXBBBBHBBBBBBBBBHBBBBBBH',
  'BH--------HBBB.-----H-S.---H',
  'BH.G..GGG.H..GH.G.G.H.SHG.GB',
  'BBHBBHSBHBBBXBHBBSBXBBBBBHBB',
  '.GHGGHE.H.....H........GGHGG',
]

const LEVEL_109: LevelDef = [
  'HH.BBBBBEHSSS.SSSHEBBBBB.HHS',
  'HSHH.G.HHSHHHHHHHSHH.G.HHSHH',
  'GHSHBHBHSHGBBHBBGHSHBHBHSHGB',
  'B.HSHHHSH.B.HHH.B.HSHHHSH.BH',
  '.BHHSHSHHB.H...H.BHHSHSHHB..',
  'HB.HHHHH.BH.BBB.HB.HHHHH.BHB',
  'HBH.....HBHB.G.BHBH.....HBHP',
  'HB.HHHHH.BH.BBB.HB.HHHHH.BHB',
  '.BHHSHSHHB.H...H.BHHSHSHHB..',
  'X.HSHHHSH.B.HHH.B.HSHHHSH.BH',
  'GHSHBHBHSHGBBHBBGHSHBHBHSHGB',
  'HSHH.G.HHSHHHHHHHSHH.G.HHSHH',
  'SH.BBBBB.HSSSHSSSH.BBBBB.HSS',
  'SH.H.G.H.HSSHHHSSH.H.G.H.HSS',
  'SH.HBHBHEHHSHHHSHHEHBHBH.HSS',
  'HSHSHHHSHSHHHHHHHSHSHHHSHSHH',
]

const LEVEL_110: LevelDef = [
  '......S-------..---.HHBBH..T',
  'G...EGS------GBB...HHBBHH..T',
  'BBBHBBS.....GBB...HHBBHHG..T',
  '...H..S....GBB...HHBBHHG.SST',
  'G..H.GS...GBB...HHBBHHG.SS.T',
  'BBBHBBS..GBB...HHBBHHG.SS..T',
  '..PH..S.GBB...HHBBHHG.SS.GGT',
  'BBBH.GSGBB...HHBBHHG.SS.HBB.',
  'BBBHBBSBB...HHBBHHG.SS..HGG.',
  'BGBH..S.G..HHE.HHG.SS.HBBBB.',
  'BBBH.GSBBBBBBBBBBBHS..HG.EG.',
  'GBBHBBS-----------HS.HBBBBB.',
  'BBBH.GSG.G..H......S.HG...G.',
  'BSSSSSSBBB..H.BBBB.S.HBBBBB.',
  '...........EHBBGGBBS.HG...G.',
  'BBBBBBBBBBBBSBBBBBBS.BBBBBBB',
]

const LEVEL_111: LevelDef = [
  '............HHH.............',
  '...........HHHH.............',
  '.............HH.............',
  '..E.........HHHH.........E..',
  '-----------HHHHHH-----------',
  '-----------HHHHHH-----------',
  '.----------HHHHHH----------.',
  '...--------HHHHHH--------...',
  '.....------HHHHHH------.....',
  '........---HHHHHH---........',
  'G.G.G.G.G..HHHHHH..G.G.G.G.G',
  '...........HHEPHH...........',
  'BBBBBBBBBBBHHBBHHBBBBBBBBBBB',
  'BBBBBBBBBBBHHBBHHBBBBBBBBBBB',
  '.G.G.G.G....H..H....G.G.G.G.',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_112: LevelDef = [
  '.....................SSSSSSH',
  '--------------..E..........H',
  'H............HSSSSSSS.HB.HTB',
  'H.EHSH.......H-----H.BH.BH..',
  'SSSSSHSHS.P........H..BB.TBX',
  'H----H.HBXBBBSSS.BBH.BBHTTBX',
  'H....H.HB.GB...G...H.B.HB--X',
  'H......HB..GBBBB.SSH.GHBG.GG',
  'H......HB.EBBBBB...H.BHB...B',
  'HXG.....B.BBBBBG.SSHTTHBHBBB',
  'H.B.....B.GBBBBB.G.H..B.HBB.',
  'H..B....B.BBBBBB.HSH.BBBH.BB',
  'H...B...BH.GBG.B.H.H..B.HB.G',
  'H....B...HBBBBBB.HSH.B.BB.BB',
  'H.......B..........H........',
  'BBSSSBBBBBBBBBSSSSBSBSSSBSSS',
]

const LEVEL_113: LevelDef = [
  'T...........................',
  'T...........................',
  'BBBBBBBBBBBBBBBHBB.G......P.',
  '....E.....E....HBBXBSSSSSSSH',
  'G..HHHHHHHHHHH.H...........H',
  'BG.H..HHHHHHHH.H.G.G.HBBBBBH',
  '.BGH..H........H.BTB.BBBBBBH',
  '..BH..HG.G.G.G..H.B........H',
  '...BG.HBXBXBXB.H.....EG.G.GH',
  '....B.H.........H....BHBBBBH',
  '......H.H.H.H..H......H.....',
  '......H.........H.....H.E...',
  '.......H.H.H...H......BBBBBH',
  '........H.H.H...H..........H',
  '....E....GTB...H...E.......H',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_114: LevelDef = [
  '.......--..........--....--.',
  '.BBBBBBG-HBBBBBBBBH-GBBBBG-.',
  '.BBBBBBBGHBBBBBBBBHGBBBBBBG.',
  '.BBBBBBBBHBBBBBBBBHBBBBBBBB.',
  '.BBB.BBBBHBBB.....HBBB...BB.',
  '.BBB..BBBHBBBGGG..HBBBGGG--.',
  '.BBB..BBBHBBBBBB..HBBBBBBG-.',
  '.BBB..BBBHBBBBBB..H.BBBBBBG.',
  '.BBB..BBBHBBBBBB..H..BBBBBB.',
  '.BBB.GBBBHBBB.....H.....BBB.',
  '.BBBGBBBBHBBBGGGGGHBBGGGBBB.',
  '.BBBBBBBBHBBBBBBBBHBBXBBBBB.',
  '.BBBBBBB.HBBBBBBBBH.BXBBBB..',
  '.BBBBBB..HBBBBBBBBH..XBBB...',
  '..E..E...H...P....H...E..E..',
  'BBBBBBBBBTBBBHHBBBTBBBBBBBBB',
]

const LEVEL_115: LevelDef = [
  '...........................T',
  '--------.BH............G..GT',
  '...GBG..HBHBSBSBSBSBSXSBSBSB',
  '..GB.BG.HBH....G...G..------',
  '.GB...BGHBBSBSBSBSBSBH.....H',
  '.B.....XHBSSSSSSSSSSSH..G..H',
  '........H----------HBBBXBBBH',
  '...................HB......H',
  '..G.PG.............HB......H',
  'HBBBBBBBH.E.G..G...HB.G..GEH',
  'H.EG..G.HBSBSBSBSBSBSSBSXSBH',
  'HBBBBBBBHBBBBBBG.BBB.......H',
  'H..G.G..HBBBBBBBB.BB.......H',
  'HBBBBBBBHBBBBBBBBB.B.......H',
  'H...G.G.HBBBBBBBBBB..G..G..H',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_116: LevelDef = [
  'BBTBSBSBSBSBSSB.BTBS.BBTBBBB',
  'BBTBBBBBBSBSSHS.STSB.B.T..HB',
  'BST......BS..H...T.G..ET..HB',
  'BBBXBBH------HBBXBBBBBBBBBHB',
  '.P.G..HGHBSG.H.S..SBS..B..HB',
  'BBBBBHBBHSBS..G.S....S.---HB',
  '..SB.HS.HSSSBSSB.S..-----BHB',
  'G.E..H..H..B---------S.GBBHB',
  'BXSBBH..HGSSBG.BSG..S..BB.HB',
  'SX.S.H..GSBSSBG.SB---HB...HB',
  '..B..H.GS.GGG.SG..S..H....H.',
  'H----HGS.HBSB..SG...BHBBBBBB',
  'H.H..SS--H......S..G.H.SSSSS',
  'H.HBSBGG.H--H..H.BBBBH..S..B',
  'H.HG.GBBGEGGH--H..BBSH...EGB',
  'BBBBBBBBBBBBH.GHGBBBBBBBBBBB',
]

const LEVEL_117: LevelDef = [
  '............BBB............T',
  '....G..E.G..SSS.....GE..G..T',
  'HBBBBBBBBBBBBBBHBBBBBBBBBBBB',
  'H----------.SSSH............',
  '...........HBBBH..---------.',
  '.----------HSSSHG..........H',
  'H.G..----P..BBBBBB.......GHB',
  'BBBBB....BH.SSSSSS....EGHBBB',
  '..-.B....BH.BBBBBB...GHBBBBB',
  'BBGHB....BH.SSSSSS.GHBBBBBBB',
  'GBBHB....BH-----.GHBBBBBBBBB',
  'BBGHB....BH.SSS.HSSSSSSSSSSS',
  'GBBHB.GG.BH.BBB.H...........',
  'BBGHBBBBXBH.SSS.HBBBBBBBBBBH',
  'GBBH..E...HGBBBGHBG........H',
  'BBBBBBBBBBBBSSSBBBSSSSSSSSSS',
]

const LEVEL_118: LevelDef = [
  '----------------............',
  '.....G..........HE..........',
  '....GGG........HHH..........',
  '....GGG........HHH..........',
  '...GG.........HH............',
  '.GG.GGG.....HH.HHH..--------',
  'GG.GG..GG..HH.HH..HH...E....',
  '...HH.........HH......HHHHH.',
  '.E.HHH........HHH.....GGGGG.',
  'HHHH.HH....HHHH.HH....HHHHH.',
  '.....HH.........HH....GGGGG.',
  '.....HH.......P.HH....HHHHH.',
  'BBBBBBBBBBBBHBBBBBBBBBBBBBBB',
  '............H...............',
  '............H...............',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_119: LevelDef = [
  '........................T...',
  '...G....................T...',
  'HSBB....................TSSH',
  'HSGBB.G................GTSSH',
  'H..BGBBB..........E.BBBBBBBH',
  'H..B.B..BBBG.....BBB.G.....H',
  'H--..BG.B..B..G.BBG.SSSS...H',
  'H..BBBBBB...BBBXB......BBBSH',
  'HG.P.............BSSSHB.G..H',
  'HSSSS--------........HBBBG.H',
  'H...S....EGGGG.......H..BBBB',
  'H.G.SG..SSSSSSSSSS...H.GS..G',
  'HBBBBB...............HBBSSBB',
  'H----H------.........H......',
  '.....H...............HE.....',
  '...G.H...BBBBBBBBBBBBBBBBBBB',
]

const LEVEL_120: LevelDef = [
  '.............T..............',
  '.............T..............',
  '.........H...T............H.',
  '...BBBBBBH...H------------H.',
  '...B..G.BH...H..........E.H.',
  '...B....BH...HSSSSSSBBSSBBSS',
  'SBSSBSSBSSBSSHB-----BXBBB..B',
  '.GE.G.....G..HB.H...B--.B..B',
  'BBBBBBBXBBBBBHB.HBGGBGBHBG.B',
  '.------------HB.HBBBBXBHB..B',
  'HE...........HB.HG...--HHHBB',
  'HBBBBBBBBBBBBHBBBBBBH.G..H..',
  'H...........PH......HBB..HHH',
  'HGBBBBB.G.BBBHBB.G.BHBG--..H',
  'HBB.G.BBBBBG.HGBBBBBHBBG.BBH',
  'BBBBBBBBBBBBBBBBBBBBH..BBBBB',
]

const LEVEL_121: LevelDef = [
  '............................',
  'BBBBBBHT............THBBBBBB',
  'BBBHHHGT............TGHHHBBB',
  'HHBBBHHHG..........GHHHBXBHH',
  'GHHHBXBHHHGE....EGHHHBBBHHHG',
  '..GHHHBBBHHHG..GHHHBXBHHHG..',
  '....GHHHBXBHHHHHHBBBHHHG....',
  '......GHHHBBBHHBBBHHHG......',
  '........GHHHBHHBHHHG........',
  '......GHHHBBBHHBBBHHHG......',
  '....GHHHBBBHHHHHHBXBHHHG....',
  '..GHHHBXBHHHG..GHHHBBBHHHG..',
  'GHHHBBBHHHG......GHHHBXBHHHG',
  'HHBXBHHHG..........GHHHBBBHH',
  'BBBHHHGT............TGHHHBBB',
  'BBBBBBHT.......P....THBBBBBB',
]

const LEVEL_122: LevelDef = [
  'T...........................',
  'T......E..........G.........',
  'T.SSHSSSS.........SSSSHSSSSS',
  'T...H....BG......B....HB.---',
  'T---H-----B.....B-----HSH..G',
  'BG..H..G...B...B......HBH--.',
  '.BE.H---.BH.B.B...G...HS...H',
  '..B.....B.H..X........HBG..H',
  'P..B...B..H.........G.HS.--H',
  'SSB.B.B...HB.------.B.HBH...',
  '....BX....H.B.G....B..HSH.E.',
  'GHBBB.....H..B....B.G.HBBBBH',
  'BHS-------H...B..B..BBHBBBBH',
  '.H.............XX.....H....H',
  '.H....................H....H',
  'SSSSSSBBBBBBBSSSSBBBBSSSSSSS',
]

const LEVEL_123: LevelDef = [
  '..............T.............',
  '...--------..-T---..........',
  '..H........H-.....H.HBBBBH..',
  '..H-------EH------.HB.H-.BH.',
  '..H.......HB..---.HB..H.G.XH',
  '..H......HX.BH...HB...H...GB',
  '..H..--.HB...BH.-.P---H----B',
  'H.BHHT.HBGHBB.BH..B........B',
  'HB.BHT.HBBBBBBBH..BBBB.BBBBB',
  'BBXBBT.HB..BG.BH-H....-...EH',
  'BBXBBT.HBBBBBBB..HBBBB.BBBBH',
  'B.G.BT.HB.GB..BH.HBGBB.BBBBH',
  'BBBBBT.HBBBBBBBH.HBBBB.BBGBH',
  'BBBBBT.HB..BG..H.HB....B...H',
  'B...BT.HBBBBBBBH.HBBXBBBXBBH',
  'B.G..TBH......BHBH...B..G..H',
]

const LEVEL_124: LevelDef = [
  'T..........................T',
  'T..........................T',
  'T-----H.....H------HB.....BH',
  '......H-----H......HB.G...BH',
  '.G....H.....H.E.G..HBBBBBXBH',
  'BBB.G.BHH...BBBBBBBBBBBBBXBH',
  'BBBBBBB.H.G..........G.....H',
  'BBBBBG..HBB...GBG...BB.....H',
  'BBBBBBG.HBB..GBBBG..BB.....H',
  'BBBBBBBGHBB.GBBBBBG.BB.E.G.H',
  'BBBBBBBBHBBXBBBBBBBBBBBHSSBH',
  'B......EH..............H.BBH',
  'B..G..BBH.......P......H.BBH',
  'BBBBBBBBH----HBBBBHG---H.BBH',
  'B..G....H..G.HBBGBHB..BHGBBH',
  'BBBBBBBBBBBBBBBBBBHBBBBHBBBH',
]

const LEVEL_125: LevelDef = [
  '....------..............-...',
  '.BBB......H--...E..HBBBB....',
  '.BG......H--.BBBBBBHBBBB....',
  '.BBB.....--..XBBBBXHBGGB....',
  '.....BBBX....XBBBBXHBBBB....',
  '.....BBBX.BB-XBGGBXH....XBBB',
  '.....BGGX.BB.XBBBBXH....XBBB',
  '.....BBBX..........H....XGGB',
  '...................H....XBBB',
  '.........XBBX......H........',
  'XBBBX....XGGX......HXBBB....',
  'XBBBX....XBBX......HXBBB.BB.',
  'X.G.X..............HXGGB.BB.',
  'XBBBX..............HXBBB....',
  '..............E....H.P......',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_126: LevelDef = [
  '...G......-.-..E...-......-E',
  'HBBB.HBBBBGBGBBBBBH.-....-.H',
  'H..G.HBBBBBBBBBBBBH.-G.-.G.H',
  'HBBB.HBBGBBBBBGBBBH-..-.-.-H',
  'H..G.HBBBBBBBBBBBBH.G...G..H',
  'HBBB.HBGBBBBBBBGBBH.--..-..H',
  'H..G.HBBBBBBBBBBBBH.-.G.-G-H',
  'HBBB.HBBGBBBBBGBBBH...-..-.H',
  'H..G.HBBBBBBBBBBBBH..-.-...H',
  'HBBB.HBBBGBBBGBBBBH-..-.-.-H',
  'H..G.HBBBBBBBBBBBBH..G...-.H',
  'HBBB.HBBBBGBGBBBBBH...--.G.H',
  'H..G.HBBBBBBBBBBBBH.-..-.-.H',
  'HBBB.HBBBGBBBGBBBBH.G.-.-.-H',
  'H.E..HBBBBBBBBBBBBH.....P...',
  'HBBBBHBBGBBBBBGBBBHBBBBBBBBB',
]

const LEVEL_127: LevelDef = [
  '......T....................T',
  '......T......E.............T',
  '---.E.T------BBBBBH....E...T',
  'HBBSBBB.BBBBBBBHGBBBBBBBBBBH',
  'HBBGBBB.SG...HBHBB...G...G.H',
  'HBBBBBB.SSSSSHSH...-------.H',
  'H........----H.H...H.......H',
  'BBXBBBH........H...H..B....H',
  '---...HBBBBBB.BBBBBBBHBBBBBB',
  'G...HBB.....----B.HHHHHHHH--',
  '....HB..SSSH....BGHHHHHHHH.G',
  'HBBBB..B...SSSH.B-HHHHHHHH.-',
  'H.....B..HBBBBH.BGHHHHHHHH..',
  'H...HB...HBBBBH.B-HHHHHHHH..',
  'HP..HBH..HB.GBH.BBBBBBBBBBBH',
  'BBBBBBBBBBBBBBB............H',
]

const LEVEL_128: LevelDef = [
  '.-........................-.',
  'H.BBBBBBBBBBBBBBBBBBBBBBBB.H',
  'H.B....B..G..GB.......B..B.H',
  'H.B.G..BBBBXBBB.......B..B.H',
  'H.BXBBBB.....B.GE.G...B.GB.H',
  'H.B...B......BBBBBBBBBBBBB.H',
  'H.B.G.B......B......B....B.H',
  'H.BBBBB..G.E.B......B....B.H',
  'H.B...BBBBBBBBB.....B..G.B.H',
  'H.B......B....BG..E.BBXBBB.H',
  'H.B.G..G.B....BBBBBBB....B.H',
  'H.BBBXBBBB....B...B......B.H',
  'H.B.G.BG...EG.BG..B.G....B.H',
  'H.BBBXBBBBBBBBBBXBBBBBBXBB.H',
  'H...........P......E.......H',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_129: LevelDef = [
  '.............HH.............',
  '..EH.........HH.........H.E.',
  '.BBHBB.....BBHHBB.....BBHBB.',
  'BBGHGBB...BBBHHBBB...BBGHGBB',
  'B..H.....BBG.HH.GBB..B..H...',
  'BBGHG.---BB..HH......BBGHG..',
  '.BBHBB...BBG.HHEG.....BBHBB.',
  '..GHGBB...BBBHHBB......GHGBB',
  '...H..B....BBHHBBB.--...H..B',
  'BBGHGBB....G.HH.GBB..BBGHGBB',
  '.BXHXB.......HH..BB...BBHXB.',
  '...H.....BBG.HHEGBB.....H...',
  '..........BBBHHBBB..........',
  '...........BBHHBB...........',
  '........P....HH.............',
  'BBBBBBBBBBBBBHHBBBBBBBBBBBBB',
]

const LEVEL_130: LevelDef = [
  'H...........................',
  'H..--......-----------------',
  'H...T.....GH....G....H...E.H',
  'BBB.BBBBBBBH-------H.H.HSSSS',
  '.G.........H.G.....H.H.H....',
  'SSSHBBB.E..H-------H.H.SSSSH',
  '...H.G.BBBBB....G..H.H.....H',
  '.P.H.BBBBBGB-------H.H.HSSSS',
  'HB.H---------------H.H.H.G..',
  'HBBBBBBBXBBBBB...E...H.SSSSH',
  'HG..BBBB.....BG..BBBBH.....H',
  'HBBBBBBBBBBBBBSS.BBBBBBHBBBB',
  'HSBBBBBBBBBBBB...BBBBBBHBBBG',
  'HSBBBBBBBBBBBBHS.BBGBBBHBBBB',
  'HS.GBBBBBBBBBBHS.......H....',
  'H.BBBBBBBG....HSBBBBBBBBBBBB',
]

const LEVEL_131: LevelDef = [
  '............T...............',
  'B.........BGTGB.........B...',
  '.B---H-----BHB-----H---B....',
  '..BG.H.E...GHG...E.H.GB.....',
  '...B-H-H---BHB---H-H-B......',
  '....B..H..X.H.X..H..B.......',
  '.H---B.H.B--H--B.H.B------H.',
  '.H-H..BHB.......BHB.....H-H.',
  '...H..BHB.......BHB.....H...',
  '.H-H..BHB.P.G...BHBBBB..H-H.',
  '.H....BHBBBBBBBBBHBBBB....H.',
  '.H-H..BHB.BBBBB.BHBBGB..H-H.',
  '..GH..BHB.BBGBB.BHBBBB..HG..',
  '.H-HE.BHB.BBBBB.BHB....EH-H.',
  '.H----.H.-.....-.H.-------H.',
  '.H....BHB.BBBBB.BHB.......H.',
]

const LEVEL_132: LevelDef = [
  'BT.........................B',
  'BT-------------------------B',
  'BT.......XBBBHBBBX.........B',
  'BT....GXBX...H...XBB.G.....B',
  'BT..GXBXGGGGGHGGEGGBXB.G...B',
  'BT.BBXBXBBBBBHBBBBBBXBXB.G.B',
  'BBBB.........H.........BXBXB',
  'BB.....GGGG..HE.GGGG.....BXB',
  'B....HBBBBBBXHBBBBBBBH.....B',
  'B....H.......H.......H.....B',
  'B...GH..GGGGGH.G.GGGGH.E...B',
  'B.HXBBBBBBBBBHXBBBBBBBBBH..B',
  'B.H..........H..........H..B',
  'B.H..........H..........H..B',
  'B.H..........H..P.......H..B',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_133: LevelDef = [
  '-------------H--------------',
  '.G......G....H...G...G.EG..G',
  'EG..G....E.G.H.G...G.G......',
  '.BXBBXBH.HBXBBBBH.HBXB......',
  '.BXBBXBBHHBXBBBBXHHBXB......',
  '.BXBBXBBXHBXBBBBXBHBXB......',
  '.BXB..BBXHBXB..BXBHBXB......',
  '.BXB..BBXHBXB..BXBHBXB......',
  '.BXB..BBXHBXB..BXBHBXB......',
  '.BXB..BBXHBXB..BXBHBXB......',
  '.BXB.GBBXHBXB.GBXBHBXB......',
  '.BXBXBBBXHBXBXBBXBHBXBBBXBB.',
  '.BXBXBBB.HBXBXBBX.HBXBBBXBB.',
  '.BXBXBB..HBXBXBB..HBXBBBXBB.',
  '.........H...P....H.........',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_134: LevelDef = [
  'GE.....BBBBBBBBBBBBBBBBBBBBB',
  'BBH....BBBBBBBBBBBBBBBBBBBBB',
  'HBBBBH....BBBBBBBBBBBBBBBBBB',
  'HBBBBBBBH.E..BBBBBBBBBBBBBBB',
  'HBBBBB.BBBBH....BBBBBBBBBBBB',
  'HBBBBB.BBBBBBBH....BBBBBBBBB',
  'HBBBBB.BBBBBBBBBBH.E..BBBBBB',
  'HBBBB.G.BBBBBBBBBBBBH....BBB',
  'HBBBBBBB.G.BBBBBBBBBBBBH....',
  'HBBBBB.BBBB.G.BBBBBBBBBBBBBH',
  'HBBBBB.BBBBBBB.G.BBBBBBBBBBH',
  'HBBBBB.BBBBBBBBBH.G.BBBBBBBH',
  'HBBBBB.BBBBBBBBBHBBB.BBBBBBH',
  'HG...G...G...G.BHBBB.BBBBBBH',
  'BBBBBBBBBBBBBB..HBBB......PH',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_135: LevelDef = [
  '.......T....................',
  '.......T....................',
  '.......T...HSSSSSSSSSSSSSSSS',
  'BBHHBBBHBBBH.....E...-------',
  'BGBHB.BHB.BHBBBBBBBBBBBB..G.',
  'B.BHBGBHBGBHHHHGHHHHGHHHBBBH',
  'BXHHBBBHB.BHHSSSSHHSSSHH...H',
  'HHHHHHHHHHHHHS..GHHS..HHBBHG',
  'HH....H.BB.HHS.-SHHS.GHHB.HB',
  'HH.BBBH.BGBHHSSSSHHSSSHHBH.B',
  'HH.BG.H..BBHH----.HHHHHHBH..',
  'HH.BB.H.B.BH..G...HHHHHBBBBH',
  'HH....HPBB.HBBBBBBB..GHBBBGH',
  'HHHHHHHSSSSHBHHHHHS.BBHBBB.H',
  'H.....G..SSHBH.H.HS.BBH.BBHB',
  'BBBBBH...E..BH.HGHS..GHB.EHB',
]

const LEVEL_136: LevelDef = [
  '.....................EEE....',
  '..................GGGGGGT...',
  '...........GGGGGGTBBBBBBB...',
  '....GGGGGGTSSSSSSS..........',
  '...TBBBBBBB.................',
  '...TT.......................',
  '....T.......................',
  'GGGGT.......................',
  'BBBBH.......................',
  'BBBBBBBBBBH.................',
  'BBBBBBBBBBBBBBBH............',
  'BBBBBBBBBBBBBBBBBBBH........',
  'BBBBBBBBBBBBBBBBBBBBBBH.....',
  'BBBBBBBBBBBBBBBBBBBBBBBBH...',
  'BBBBBBBBBBBBBBBBBBBBBBBBBH..',
  'BBBBBBBBBBBBBBBBBBBBBBBBBHP.',
]

const LEVEL_137: LevelDef = [
  'T...........................',
  'T...G...G...GE.EG...G...G...',
  'BBBBBBBBBBBBBBTBBBBBBBBBBBBB',
  '..............H.............',
  '.............BHB............',
  '.............GHG............',
  '...E........BBHBB.......E...',
  '...H........G.H.G.......H...',
  '..BHB......BBBHBBB.....BHB..',
  '..GHG......G..H..G.....GHG..',
  '.BBHBB....BBBBHBBBB...BBHBB.',
  '.G.H.G....G...H...G...G.H.G.',
  'BBBHBBB..BBBBBHBBBBB.BBBHBBB',
  'G..H..G..G....H....G.G..H..G',
  '...H..........H.P.......H...',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_138: LevelDef = [
  '.............T..............',
  '.............T..............',
  '..........E..T..G---........',
  '.--------HSSSSBXBB..H.......',
  'H........H.......G..H.......',
  'H......BBBBBBSSSBBBBBBB.....',
  'H......BG.B...B...B...B.....',
  'H.E.GG.B..B..GB.GGB.GGB.G...',
  'HBBBBBBB..BBBBBBBBBBBBBBBBB.',
  'HB..B.BBBBB.....B...........',
  'HB.GB.G..B...HG.B.P......G..',
  'HBBBBBBBBBBBSHSBBBBBBBXBBBBB',
  'H............H..........---.',
  'H............H.........H..G.',
  'H........G...H.........H.BBB',
  'BBBBBBBBBBBBBH....G.E..H..G.',
]

const LEVEL_139: LevelDef = [
  'T...............T..SBBBB....',
  'TBBBBBBBBBBBBBBBT..S.GHB.G..',
  'T-----------H..BH--SBBHB.SSS',
  'GHBSB.....G.H--BH...G.HB...H',
  'SH...BB.....H..BH..SBBHB..GH',
  'SHBB..GB...PH..BH.GSE.HBH--H',
  'HH.GBBBBBBBBH..BH..SBHBBH..H',
  'H..BBB.....SH..BH....H..H.G.',
  'H...BB....GSH..BBH...H..HBBB',
  'HH...BBBBBBSHE..BBBH.H..H...',
  'SHBBB------SBBH...BBBHH.HBBH',
  'BH....E.......BSH...BBHB...H',
  'BHBBBBBBBH......BSH...HB...H',
  'BHBBGBBBBHBBBBBHBBBSSHHBBB.H',
  'BHBBBBBGBHBBBBBHG..G.HHBG..H',
  'BHBBBBBBBBBBBBBBBBBBBHBBBBBH',
]

const LEVEL_140: LevelDef = [
  '............................',
  '..........TTTTTTTT..........',
  '..........HBBBBBBH..........',
  '........E.HB.E..BH.E........',
  '..........HB..G.BH..........',
  '.....HBBBBBBBBBBBBBBBBH.....',
  '.....HB....B....B....BH.....',
  '.....HB....B....B....BH.....',
  '.....HB....B....B....BH.....',
  '.....HB..G.BE.G.B..G.BH.....',
  'HBBBBBBBBBBBBBXBBBBBBBBBBBBH',
  'HB....B....B....B....B....BH',
  'HB....B....B....B....B....BH',
  'HB..G.B..G.B..G.B..G.B..G.BH',
  'HBHBBHBHBBHBHBBHBHBBHBHBBHBH',
  'H.HBBH.HBBHPHBBHEHBBH.HBBH.H',
]

const LEVEL_141: LevelDef = [
  '----------........----------',
  'H.........BBBBBBBB.........H',
  'H.......BBBBBBBBBBBB.......H',
  'H...E..BBBBBBBBBBBBBB..E...H',
  'H.SSSSBBBBBBBBBBBBBBBBSSSS.H',
  'H........BBBBBBBBBB........H',
  'H.SH........BBBB........HS.H',
  'SSSH....................HSSS',
  '...H..G..G..G..G..G..G..H...',
  '...H....................H...',
  '...H........BBBB........H...',
  '...H.....BBBXXXXBBB..P..H...',
  '...H..BBBXXXXXXXXXXBBB..H...',
  '...H...XXXXXXXXXXXXXX...H...',
  '...H....XXXXXXXXXXXX....H...',
  '...H......XXXXXXXX......H...',
]

const LEVEL_142: LevelDef = [
  '-----------.................',
  '...........H.....B...-.-....',
  '..G..G..G.EH----.BBBB.H.BBBB',
  'BBBBBBBBBBB.....HBBBB.H.XBBB',
  'GG.......GG.----HBBBB.H.XBBB',
  'BBG.....GBBH.....B.BB.H.XGGB',
  'BBBG...GBBBH----.B.BB.H.XBBB',
  'BBBBG.GBBBB.....HB.BB.H.XGGB',
  'BBBBBGBBBBB..E..HB.BB.H.XBBB',
  'BBBBBBBBBBBHBBBBBBGGB.H.XGGB',
  '...........H.....BBBB.H.XBBB',
  'BTB....P...H.........EH.XGGB',
  'BTBBBBBBBBBBBHBBBBBBBBBBXBBB',
  'BT....BBBGBBBHBBBBBG........',
  'BT....BBBBGBBHBBG.GBBH.....G',
  'BTG..GBBBBB..H..BBBBBBBBBBBB',
]

const LEVEL_143: LevelDef = [
  'BBBBBBBBTBBBBBBBBBBBBBBBBBBB',
  'P.S..SSST...SH.B...H-------.',
  'BH...H.SHSS.SHGBHSSH........',
  'GHSSBH.SHSS..H..H.........G.',
  'BBH..H.SH..BBBHSH-----......',
  'GSHBBSGSHBB---HSH.......BBBB',
  '..H....SHS.GS.HSBB...G......',
  '.EH..G.SHSBBBBHS.H.......E..',
  'SSBBHB.SHS....H--HSSSSSSSSSS',
  'H..SHB..HSBBBBBB.H...S-----S',
  'HB..HBBBHS.GBG..BBBH.S.H...S',
  'HS.HSS.SHS..B......H...H...S',
  'HS.HS.GSH...BBBBBBBBBBBHS..S',
  'H.BBB.SSHSBBB..........H...S',
  'H....E..HSG.SH.G....G..H...S',
  'BBBBBBBBBSBBGHSSBBBBSSSH..GS',
]

const LEVEL_144: LevelDef = [
  '............................',
  '.....---T......---....-...--',
  'H...H..-BSSSSSS...BBBB.SSH..',
  'HG..HG..B...SG...........H.G',
  'BBH-SSH.SH..SSBS.XXXXBB.HBXB',
  '.GH.EGH.SH..SG..........H...',
  'HBB-HSS.SHH.SSBH.X....X.H...',
  'HG..HG..S.HH..SH..BGGB..H...',
  'BBH-SSH.S..HH.SH...BBH--H.G.',
  'EGH..GH.S...HHSH.....H..BBXB',
  'HBB-HSS.S....HSH..E..H......',
  'HG..HGE.S.....SHSSSSSSSSH.G.',
  'BBH-SSH.S.....SHB..G.G.BHBXB',
  '.GH..GH.S.....SHBHBSBSBBH...',
  'HBB-SSS.SEGGHB.HBH.G.G..H...',
  'H.P.....BBBBBBSSBBSBSBSBSBSB',
]

const LEVEL_145: LevelDef = [
  '......E...T.......T...E.....',
  '...........T.....T..........',
  '............T...T...........',
  '..........GBBBHBBBG.........',
  '..........BGBGHGBGB.........',
  '..G......BGH.HBH.HGB....G.G.',
  '..BBHBHBBBBBBH.HBBBBBBHBHBB.',
  '.GB.HBH......HHH......HBHGB.',
  '.B.HHBHHHHHHHHHHHHHHHHHBHH.B',
  '.BHEG.BHHHHHHHBHHHHHHHB.GEHB',
  '..BBBH.BH.G..H.H..G.HB.HBBB.',
  '...GBBHBBBBBBBHBBBBBBBHBBG..',
  '...BB.H.....G.H.G.....H.BB..',
  '...B.HBBHHHHHHBHHHHHHBBH.B..',
  '.G..HBBBHHHBHHHHHBHHHBBBHPG.',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_146: LevelDef = [
  'B....-.....P....-....B.G....',
  'BBBBH.BBBBBBBBBB.HBBBB.BBBBH',
  'BBBBH.B..BBBBB.B.HBBBB...G.H',
  'BGBBH.B.BBBBB..B.HBBGB.HBBBB',
  'BBBBH.B..BBBBB.B.HBBBB.HG...',
  'BBGBH.B.BBBBB..B.HBGBB.BBBBH',
  'BBBBH.B..BBBBB.B.HBBBB....GH',
  'BGBBH.B.BBBBB..B.HBBBB.HBBBB',
  'BBBBH.B..BBBBB.B.H.BBB.H.G..',
  'BBGBH.B.BBBBB..B.HBBBB.BBBBH',
  'BBBBH.B...BBBB.B.HBGBB..G..H',
  'BGBBH.BGBBBBBGGB.HBBBB.HBBBB',
  'BBBBH.BBBBBBBBBB.HBBG..H..G.',
  'BBGBH.BBBBBBBBBB.HBBBB.BBBBH',
  'BBBBH..E.....E...HBBBB..E..H',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_147: LevelDef = [
  '................T...........',
  '.E-.........-P..T.....-.....',
  '.H.H.......H.H..T....H.H...H',
  'H..HH.....H...H.T...H...H..H',
  '.BGH.H...H.BGB.HT..H.BGB.H-H',
  '.BBH..---HEBBB.H---HEBHB...H',
  'SBBHBBXBBSBBSBBSBBXBBSHBXBBH',
  'B..H..X..B..GBBB..GB.BH.X..H',
  'B--H--X--B.HB----H----H-B--H',
  'B..H..X..B.HB..B.HXH.BE.G..H',
  'BXSHBSBXSBBHBBSBBSXHSBBSBXBH',
  '.XBBBB...BBHBB...BXHBB...XBH',
  '...H---.--BHB--.--XHB--.--BH',
  '..BHB..G..BHB..G..BH...G..BH',
  '.GBHB..S..BHB..S..BHB..S..BH',
  'BX.H.XBSBB.H.BBSBB.H.BBSBX.H',
]

const LEVEL_148: LevelDef = [
  '............................',
  '..........EE.TT.EE..........',
  '.........GGGTBBTGGG.........',
  '...GGGGGTSSSSSSSSSSTGGGGG...',
  '..TBBBBBB..........BBBBBBT..',
  '..TTT..................TTT..',
  '....T..................T....',
  '....T..................T....',
  '....T..................T....',
  '....T..................T....',
  '....T..................T....',
  '....T..................T....',
  '....T..................T....',
  '....T..................T....',
  '....T..........P.......T....',
  'SBBBBBBSBBBBBSSBBBBBSBBBBBBS',
]

const LEVEL_149: LevelDef = [
  '............................',
  '.........HBB....BBH.........',
  '........HBB......BBH........',
  '.......HBB........BBH.......',
  '......HBBG..E.....GBBH......',
  '..G--HBBBBBBBBBBBBBBBBH--GE.',
  '.HBH...BBG........GBB...HBH.',
  '.HHBH...BB.G....G.BB...HBHH.',
  '.GHHBHE..BBBB..BBBB...HBHHG.',
  '..GHHBH...BBB..BBB...HBHHG..',
  '...GHHBH...BBGPBB...HBHHG...',
  '....GHHBH...BBBB...HBHHG....',
  '.....GHHBH...HH...HBHHG.....',
  '......GHHBH..HH..HBHHG......',
  'G..E...GHBBH.HH.HBBHG...E..G',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBB',
]

const LEVEL_150: LevelDef = [
  '.----........EP........----.',
  'H....BBHG..........GHBB....H',
  'H....BBHG..........GHBB....H',
  'H.....BBHG........GHBB.....H',
  'HG.G..BBHG........GHBB..G.GH',
  'HBBBBH.BBHG......GHBB.HBBBBH',
  'HG..GH.BBHG......GHBB.HG..GH',
  'HBBBBBH.BBHG....GHBB.HBBBBBH',
  'HGE.EGH.BBHG....GHBB.HGE.EGH',
  'HBBBBBBH.BBHG..GHBB.HBBBBBBH',
  'HG....GH.BBHG..GHBB.HG....GH',
  'HBBBBBBBH.BBHGGHBB.HBBBBBBBH',
  'HG.....GH.BBBBBBBB.HG.....GH',
  'HBBBBBBBBH.BBBXBB.HBBBBBBBBH',
  'HG......GH.GGBXGG.HG......GH',
  'BBBBBBBBBBBBBSSBBTBBBBBBBBBB',
]

export const LEVELS: LevelDef[] = [
  LEVEL_1, LEVEL_2, LEVEL_3, LEVEL_4, LEVEL_5, LEVEL_6, LEVEL_7, LEVEL_8, LEVEL_9, LEVEL_10,
  LEVEL_11, LEVEL_12, LEVEL_13, LEVEL_14, LEVEL_15, LEVEL_16, LEVEL_17, LEVEL_18, LEVEL_19, LEVEL_20,
  LEVEL_21, LEVEL_22, LEVEL_23, LEVEL_24, LEVEL_25, LEVEL_26, LEVEL_27, LEVEL_28, LEVEL_29, LEVEL_30,
  LEVEL_31, LEVEL_32, LEVEL_33, LEVEL_34, LEVEL_35, LEVEL_36, LEVEL_37, LEVEL_38, LEVEL_39, LEVEL_40,
  LEVEL_41, LEVEL_42, LEVEL_43, LEVEL_44, LEVEL_45, LEVEL_46, LEVEL_47, LEVEL_48, LEVEL_49, LEVEL_50,
  LEVEL_51, LEVEL_52, LEVEL_53, LEVEL_54, LEVEL_55, LEVEL_56, LEVEL_57, LEVEL_58, LEVEL_59, LEVEL_60,
  LEVEL_61, LEVEL_62, LEVEL_63, LEVEL_64, LEVEL_65, LEVEL_66, LEVEL_67, LEVEL_68, LEVEL_69, LEVEL_70,
  LEVEL_71, LEVEL_72, LEVEL_73, LEVEL_74, LEVEL_75, LEVEL_76, LEVEL_77, LEVEL_78, LEVEL_79, LEVEL_80,
  LEVEL_81, LEVEL_82, LEVEL_83, LEVEL_84, LEVEL_85, LEVEL_86, LEVEL_87, LEVEL_88, LEVEL_89, LEVEL_90,
  LEVEL_91, LEVEL_92, LEVEL_93, LEVEL_94, LEVEL_95, LEVEL_96, LEVEL_97, LEVEL_98, LEVEL_99, LEVEL_100,
  LEVEL_101, LEVEL_102, LEVEL_103, LEVEL_104, LEVEL_105, LEVEL_106, LEVEL_107, LEVEL_108, LEVEL_109, LEVEL_110,
  LEVEL_111, LEVEL_112, LEVEL_113, LEVEL_114, LEVEL_115, LEVEL_116, LEVEL_117, LEVEL_118, LEVEL_119, LEVEL_120,
  LEVEL_121, LEVEL_122, LEVEL_123, LEVEL_124, LEVEL_125, LEVEL_126, LEVEL_127, LEVEL_128, LEVEL_129, LEVEL_130,
  LEVEL_131, LEVEL_132, LEVEL_133, LEVEL_134, LEVEL_135, LEVEL_136, LEVEL_137, LEVEL_138, LEVEL_139, LEVEL_140,
  LEVEL_141, LEVEL_142, LEVEL_143, LEVEL_144, LEVEL_145, LEVEL_146, LEVEL_147, LEVEL_148, LEVEL_149, LEVEL_150,
]

export const TOTAL_LEVELS = LEVELS.length

export const LEVEL_NAMES: string[] = []
