"""
News data package.

Contains data models, sources, cache utilities, and historical data
for the news subsystem. No router or FastAPI dependencies.
"""

from .debt_ceiling_data import DEBT_CEILING_HISTORY
from .news_cache import (
    ALTSEASON_CACHE_FILE,
    ATH_CACHE_FILE,
    BLOCK_HEIGHT_CACHE_FILE,
    BLOCK_HEIGHT_CACHE_MINUTES,
    BTC_DOMINANCE_CACHE_FILE,
    CACHE_FILE,
    FEAR_GREED_CACHE_FILE,
    FEAR_GREED_CACHE_MINUTES,
    HASH_RATE_CACHE_FILE,
    LIGHTNING_CACHE_FILE,
    MARKET_METRICS_CACHE_MINUTES,
    MEMPOOL_CACHE_FILE,
    NEWS_CACHE_CHECK_MINUTES,
    NEWS_ITEM_MAX_AGE_DAYS,
    STABLECOIN_MCAP_CACHE_FILE,
    US_DEBT_CACHE_FILE,
    US_DEBT_CACHE_HOURS,
    VIDEO_CACHE_CHECK_MINUTES,
    VIDEO_CACHE_FILE,
    load_altseason_cache,
    load_ath_cache,
    load_block_height_cache,
    load_btc_dominance_cache,
    load_btc_rsi_cache,
    load_cache,
    load_fear_greed_cache,
    load_hash_rate_cache,
    load_lightning_cache,
    load_mempool_cache,
    load_stablecoin_mcap_cache,
    load_us_debt_cache,
    load_video_cache,
    merge_news_items,
    prune_old_items,
    save_altseason_cache,
    save_ath_cache,
    save_block_height_cache,
    save_btc_dominance_cache,
    save_btc_rsi_cache,
    save_cache,
    save_fear_greed_cache,
    save_hash_rate_cache,
    save_lightning_cache,
    save_mempool_cache,
    save_stablecoin_mcap_cache,
    save_us_debt_cache,
    save_video_cache,
)
from .news_models import (
    ArticleContentResponse,
    BlockHeightResponse,
    DebtCeilingEvent,
    DebtCeilingHistoryResponse,
    FearGreedResponse,
    NewsItem,
    NewsResponse,
    USDebtResponse,
    VideoItem,
    VideoResponse,
)
from .news_sources import NEWS_CATEGORIES, NEWS_SOURCES, VIDEO_SOURCES

__all__ = [
    # Data
    "DEBT_CEILING_HISTORY",
    "NEWS_CATEGORIES",
    "NEWS_SOURCES",
    "VIDEO_SOURCES",
    # Cache paths
    "CACHE_FILE",
    "VIDEO_CACHE_FILE",
    "FEAR_GREED_CACHE_FILE",
    "BLOCK_HEIGHT_CACHE_FILE",
    "US_DEBT_CACHE_FILE",
    "BTC_DOMINANCE_CACHE_FILE",
    "ALTSEASON_CACHE_FILE",
    "STABLECOIN_MCAP_CACHE_FILE",
    "MEMPOOL_CACHE_FILE",
    "HASH_RATE_CACHE_FILE",
    "LIGHTNING_CACHE_FILE",
    "ATH_CACHE_FILE",
    # Cache constants
    "NEWS_CACHE_CHECK_MINUTES",
    "NEWS_ITEM_MAX_AGE_DAYS",
    "VIDEO_CACHE_CHECK_MINUTES",
    "FEAR_GREED_CACHE_MINUTES",
    "BLOCK_HEIGHT_CACHE_MINUTES",
    "US_DEBT_CACHE_HOURS",
    "MARKET_METRICS_CACHE_MINUTES",
    # Cache functions
    "load_cache",
    "save_cache",
    "load_video_cache",
    "save_video_cache",
    "load_fear_greed_cache",
    "save_fear_greed_cache",
    "load_block_height_cache",
    "save_block_height_cache",
    "load_us_debt_cache",
    "save_us_debt_cache",
    "load_btc_dominance_cache",
    "save_btc_dominance_cache",
    "load_altseason_cache",
    "save_altseason_cache",
    "load_stablecoin_mcap_cache",
    "save_stablecoin_mcap_cache",
    "load_mempool_cache",
    "save_mempool_cache",
    "load_hash_rate_cache",
    "save_hash_rate_cache",
    "load_lightning_cache",
    "save_lightning_cache",
    "load_ath_cache",
    "save_ath_cache",
    "load_btc_rsi_cache",
    "save_btc_rsi_cache",
    "prune_old_items",
    "merge_news_items",
    # Models
    "ArticleContentResponse",
    "BlockHeightResponse",
    "DebtCeilingEvent",
    "DebtCeilingHistoryResponse",
    "FearGreedResponse",
    "NewsItem",
    "NewsResponse",
    "USDebtResponse",
    "VideoItem",
    "VideoResponse",
]
