"""
Migration 084: Speculative Weights Proposals table.

Creates `trading.speculative_weights_proposals` to back the auto-tuning
pipeline for the speculative preset signal weights. Every proposal
generated by app.services.speculative_weights_tuner lands here — both
the pending proposals surfaced to the user AND the applied / rejected
/ superseded / reverted history.

The table doubles as the source of truth for each user's currently
effective weights: the latest row with status='applied' for a given
user_id wins, falling back to the scorer's DEFAULT_WEIGHTS constant
if no row exists.

Idempotent: re-running this migration is a no-op on tables that
already exist.
"""

from migrations.db_utils import get_migration_connection, is_postgres


def run():
    print("Migration 084: Creating trading.speculative_weights_proposals...")
    conn = get_migration_connection()
    try:
        if is_postgres():
            _run_postgres(conn)
        else:
            _run_sqlite(conn)
        conn.commit()
        print("Migration 084 complete")
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def _run_postgres(conn):
    cur = conn.cursor()
    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS trading.speculative_weights_proposals (
            id SERIAL PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES auth.users(id),
            account_id INTEGER REFERENCES trading.accounts(id),
            status VARCHAR(20) NOT NULL DEFAULT 'pending',
            algorithm VARCHAR(40) NOT NULL,
            sample_size INTEGER NOT NULL,
            overall_win_rate_pct DOUBLE PRECISION NOT NULL,
            baseline_weights JSONB NOT NULL,
            proposed_weights JSONB NOT NULL,
            divergence_pp DOUBLE PRECISION,
            reason TEXT,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            decided_at TIMESTAMP,
            decided_by INTEGER REFERENCES auth.users(id),
            reverted_by_proposal_id INTEGER
                REFERENCES trading.speculative_weights_proposals(id)
        )
        """
    )
    cur.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_spec_prop_user_status
        ON trading.speculative_weights_proposals(user_id, status)
        """
    )
    # Partial index — makes the "latest applied for user X" lookup O(log N).
    cur.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_spec_prop_user_applied_decided
        ON trading.speculative_weights_proposals(user_id, decided_at DESC)
        WHERE status = 'applied'
        """
    )


def _run_sqlite(conn):
    cur = conn.cursor()
    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS speculative_weights_proposals (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL,
            account_id INTEGER,
            status VARCHAR(20) NOT NULL DEFAULT 'pending',
            algorithm VARCHAR(40) NOT NULL,
            sample_size INTEGER NOT NULL,
            overall_win_rate_pct REAL NOT NULL,
            baseline_weights TEXT NOT NULL,
            proposed_weights TEXT NOT NULL,
            divergence_pp REAL,
            reason TEXT,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            decided_at TIMESTAMP,
            decided_by INTEGER,
            reverted_by_proposal_id INTEGER
        )
        """
    )
    cur.execute(
        "CREATE INDEX IF NOT EXISTS idx_spec_prop_user_status "
        "ON speculative_weights_proposals(user_id, status)"
    )


if __name__ == "__main__":
    run()
