"""
Indicator-Based strategy parameter definitions (data-driven config).

Each dict is unpacked into StrategyParameter(**entry) by get_definition().
Extracted from indicator_based.py to keep the strategy file focused on logic.
"""

INDICATOR_PARAMS = [
    # ── Deal Management ───────────────────────────────────────────────────
    {"name": "max_concurrent_deals", "display_name": "Max Concurrent Deals",
     "description": "Maximum positions that can be open at the same time",
     "type": "int", "default": 1, "min_value": 1, "max_value": 20,
     "group": "Deal Management"},
    {"name": "max_simultaneous_same_pair", "display_name": "Max Simultaneous Deals (Same Pair)",
     "description": ("Maximum concurrent positions allowed on the same trading pair."
                     " New deals open only after all existing deals have used all"
                     " their safety orders."),
     "type": "int", "default": 1, "min_value": 1, "max_value": 20,
     "group": "Deal Management"},
    {"name": "deal_cooldown_seconds", "display_name": "Deal Cooldown (seconds)",
     "description": ("Wait time before opening a new deal on the same pair"
                     " after the previous deal closes. 0 or empty = no cooldown."),
     "type": "int", "default": 0, "min_value": 0, "max_value": 86400,
     "group": "Deal Management"},
    # ── Base Order ────────────────────────────────────────────────────────
    {"name": "base_order_type", "display_name": "Base Order Type",
     "description": "How to calculate base order size",
     "type": "str", "default": "percentage",
     "options": ["percentage", "fixed_btc", "fixed_usd"],
     "group": "Base Order"},
    {"name": "base_order_percentage", "display_name": "Base Order % of Balance",
     "description": "Percentage of available balance for base order",
     "type": "float", "default": 10.0, "min_value": 1.0, "max_value": 100.0,
     "group": "Base Order"},
    {"name": "base_order_fixed", "display_name": "Base Order Fixed Amount",
     "description": "Fixed amount for base order (BTC or USD)",
     "type": "float", "default": 0.001, "min_value": 0.0001, "max_value": 10000.0,
     "group": "Base Order"},
    {"name": "base_execution_type", "display_name": "Base Order Execution",
     "description": "Market (instant fill) or Limit (at current price)",
     "type": "str", "default": "market",
     "options": ["market", "limit"],
     "group": "Base Order"},
    # ── Safety Orders (DCA) ───────────────────────────────────────────────
    {"name": "max_safety_orders", "display_name": "Max Safety Orders",
     "description": "Maximum number of DCA safety orders",
     "type": "int", "default": 5, "min_value": 0, "max_value": 20,
     "group": "Safety Orders"},
    {"name": "safety_order_type", "display_name": "Safety Order Type",
     "description": "How to calculate safety order size",
     "type": "str", "default": "percentage_of_base",
     "options": ["percentage_of_base", "fixed_btc", "fixed_usd"],
     "group": "Safety Orders"},
    {"name": "safety_order_percentage", "display_name": "Safety Order % of Base",
     "description": "Each safety order as % of base order",
     "type": "float", "default": 50.0, "min_value": 10.0, "max_value": 500.0,
     "group": "Safety Orders"},
    {"name": "safety_order_fixed", "display_name": "Safety Order Fixed Amount",
     "description": "Fixed amount for each safety order",
     "type": "float", "default": 0.0005, "min_value": 0.0001, "max_value": 10000.0,
     "group": "Safety Orders"},
    {"name": "price_deviation", "display_name": "Price Deviation %",
     "description": "Price drop % to trigger first safety order",
     "type": "float", "default": 2.0, "min_value": 0.1, "max_value": 20.0,
     "group": "Safety Orders"},
    {"name": "safety_order_step_scale", "display_name": "Safety Order Step Scale",
     "description": "Multiplier for price deviation between orders",
     "type": "float", "default": 1.0, "min_value": 1.0, "max_value": 5.0,
     "group": "Safety Orders"},
    {"name": "safety_order_volume_scale", "display_name": "Safety Order Volume Scale",
     "description": "Multiplier for each safety order size",
     "type": "float", "default": 1.0, "min_value": 1.0, "max_value": 5.0,
     "group": "Safety Orders"},
    {"name": "dca_target_reference", "display_name": "DCA Target Reference",
     "description": "Price to calculate DCA target deviation from",
     "type": "string", "default": "average_price",
     "options": ["base_order", "average_price", "last_buy"],
     "group": "Safety Orders"},
    {"name": "dca_execution_type", "display_name": "DCA Order Execution",
     "description": "Market (instant fill) or Limit (at current price)",
     "type": "str", "default": "market",
     "options": ["market", "limit"],
     "group": "Safety Orders"},
    # ── Take Profit ───────────────────────────────────────────────────────
    {"name": "take_profit_percentage", "display_name": "Take Profit %",
     "description": "Profit target % from average buy price",
     "type": "float", "default": 3.0, "min_value": 0.1, "max_value": 50.0,
     "group": "Take Profit"},
    {"name": "take_profit_mode", "display_name": "Take Profit Mode",
     "description": ("Fixed: sell at TP%. Trailing: trail from peak after TP%."
                     " Minimum: TP% is floor, conditions trigger exit."),
     "type": "str", "default": "fixed",
     "options": ["fixed", "trailing", "minimum"],
     "group": "Take Profit"},
    {"name": "trailing_deviation", "display_name": "Trailing Deviation %",
     "description": "How far price can drop from peak before selling",
     "type": "float", "default": 1.0, "min_value": 0.1, "max_value": 10.0,
     "group": "Take Profit",
     "visible_when": {"take_profit_mode": "trailing"}},
    {"name": "take_profit_order_type", "display_name": "Exit Order Execution",
     "description": "Market (instant fill) or Limit (at mark price)",
     "type": "str", "default": "market",
     "options": ["market", "limit"],
     "group": "Take Profit"},
    # ── Slippage Guard ────────────────────────────────────────────────────
    {"name": "slippage_guard", "display_name": "Slippage Guard",
     "description": "Check order book depth before market orders to prevent excessive slippage",
     "type": "bool", "default": False,
     "group": "Slippage Guard"},
    {"name": "max_buy_slippage_pct", "display_name": "Max Buy Slippage %",
     "description": "Max % above best ask for buy VWAP",
     "type": "float", "default": 0.5, "min_value": 0.01, "max_value": 5.0,
     "group": "Slippage Guard",
     "visible_when": {"slippage_guard": True}},
    {"name": "max_sell_slippage_pct", "display_name": "Max Sell Slippage %",
     "description": "Max % below best bid for sell VWAP (fixed/trailing modes)",
     "type": "float", "default": 0.5, "min_value": 0.01, "max_value": 5.0,
     "group": "Slippage Guard",
     "visible_when": {"slippage_guard": True}},
    # ── Stop Loss ─────────────────────────────────────────────────────────
    {"name": "stop_loss_enabled", "display_name": "Enable Stop Loss",
     "description": "Enable stop loss protection",
     "type": "bool", "default": False,
     "group": "Stop Loss"},
    {"name": "stop_loss_percentage", "display_name": "Stop Loss %",
     "description": "Stop loss % from average buy price (negative)",
     "type": "float", "default": -10.0, "min_value": -50.0, "max_value": -0.1,
     "group": "Stop Loss"},
    {"name": "trailing_stop_loss", "display_name": "Trailing Stop Loss",
     "description": "Enable trailing stop loss",
     "type": "bool", "default": False,
     "group": "Stop Loss"},
    {"name": "trailing_stop_deviation", "display_name": "Trailing Stop Deviation %",
     "description": "How far price can drop from peak before stop loss",
     "type": "float", "default": 5.0, "min_value": 0.1, "max_value": 20.0,
     "group": "Stop Loss"},
    # ── AI Indicators ─────────────────────────────────────────────────────
    {"name": "ai_model", "display_name": "AI Model",
     "description": "Which LLM to use for AI spot opinions",
     "type": "str", "default": "claude",
     "options": ["claude", "gpt", "gemini"],
     "group": "AI Indicators"},
    {"name": "ai_timeframe", "display_name": "AI Check Timeframe",
     "description": "How often to ask AI for opinion (once per candle close)",
     "type": "str", "default": "15m",
     "options": ["5m", "15m", "30m", "1h", "4h"],
     "group": "AI Indicators"},
    {"name": "ai_min_confidence", "display_name": "AI Min Confidence",
     "description": "Minimum confidence % (0-100) to act on AI signal",
     "type": "int", "default": 60, "min_value": 0, "max_value": 100,
     "group": "AI Indicators"},
    {"name": "enable_buy_prefilter", "display_name": "Enable Buy Pre-filter",
     "description": "Use technical pre-filter before asking AI (saves LLM costs)",
     "type": "bool", "default": True,
     "group": "AI Indicators"},
    # ── Bull Flag ─────────────────────────────────────────────────────────
    {"name": "bull_flag_timeframe", "display_name": "Bull Flag Timeframe",
     "description": "Timeframe for bull flag pattern detection",
     "type": "str", "default": "FIFTEEN_MINUTE",
     "options": ["FIVE_MINUTE", "FIFTEEN_MINUTE", "THIRTY_MINUTE", "ONE_HOUR"],
     "group": "Bull Flag"},
    {"name": "bull_flag_min_pole_gain", "display_name": "Bull Flag Min Pole Gain %",
     "description": "Minimum percentage gain required in the pole",
     "type": "float", "default": 3.0, "min_value": 1.0, "max_value": 20.0,
     "group": "Bull Flag"},
    # ── Bidirectional ─────────────────────────────────────────────────────
    {"name": "enable_bidirectional", "display_name": "Enable Bidirectional Trading",
     "description": "Run both long and short DCA strategies simultaneously (requires USD + BTC reserves)",
     "type": "bool", "default": False,
     "group": "Bidirectional"},
    {"name": "long_budget_percentage", "display_name": "Long Budget %",
     "description": "% of bot budget allocated to long positions (buying)",
     "type": "float", "default": 50.0, "min_value": 10.0, "max_value": 90.0,
     "group": "Bidirectional"},
    {"name": "short_budget_percentage", "display_name": "Short Budget %",
     "description": "% of bot budget allocated to short positions (selling)",
     "type": "float", "default": 50.0, "min_value": 10.0, "max_value": 90.0,
     "group": "Bidirectional"},
    {"name": "enable_dynamic_allocation", "display_name": "Enable Dynamic Allocation",
     "description": "Automatically shift capital to better-performing direction (70/30 max)",
     "type": "bool", "default": False,
     "group": "Bidirectional"},
    {"name": "enable_neutral_zone", "display_name": "Enforce Neutral Zone",
     "description": "Require minimum price distance between long and short entries",
     "type": "bool", "default": True,
     "group": "Bidirectional"},
    {"name": "neutral_zone_percentage", "display_name": "Neutral Zone %",
     "description": "Minimum % distance between long and short entry prices",
     "type": "float", "default": 5.0, "min_value": 1.0, "max_value": 20.0,
     "group": "Bidirectional"},
    {"name": "auto_mirror_conditions", "display_name": "Auto-Mirror Conditions",
     "description": "Automatically create mirrored short conditions from long conditions",
     "type": "bool", "default": True,
     "group": "Bidirectional"},
]
