/**
 * Game registry and shared constants for the Games Hub.
 */

import {
  Grid3X3,
  CircleDot,
  Hash,
  Bomb,
  PenLine,
  LetterText,
  Waypoints,
  LayoutGrid,
  Layers,
  Grip,
  Table2,
  Crown,
  Triangle,
  FlipHorizontal,
  Spade,
  Dices,
  ChessKnight,
  Clover,
  Gem,
  Heart,
  Swords,
  Infinity,
  Wine,
  LayoutDashboard,
  Bug,
  Rocket,
  Pickaxe,
  Footprints,
  Shield,
  Fish,
  Zap,
  Utensils,
  Banknote,
  BarChart3,
  Handshake,
  Star,
  Building2,
  Boxes,
  Grid2X2,
} from 'lucide-react'
import { createElement, type ComponentType } from 'react'
import type { GameInfo } from './types'

export const GAMES: GameInfo[] = [
  {
    id: 'tic-tac-toe',
    name: 'Tic-Tac-Toe',
    description: 'Classic 3x3 strategy',
    icon: 'Grid3X3',
    path: '/games/tic-tac-toe',
    difficulty: 'easy',
    sessionLength: '1-2 min',
    category: 'strategy',
    multiplayer: ['vs', 'first_to_win'],
  },
  {
    id: 'connect-four',
    name: 'Connect Four',
    description: 'Drop discs, line up four',
    icon: 'CircleDot',
    path: '/games/connect-four',
    difficulty: 'medium',
    sessionLength: '3-5 min',
    category: 'strategy',
    multiplayer: ['vs', 'first_to_win'],
  },
  {
    id: '2048',
    name: '2048',
    description: 'Slide and merge to 2048',
    icon: 'Hash',
    path: '/games/2048',
    difficulty: 'medium',
    sessionLength: '5-15 min',
    category: 'puzzle',
    multiplayer: ['best_score'],
  },
  {
    id: 'minesweeper',
    name: 'Minesweeper',
    description: 'Clear the minefield',
    icon: 'Bomb',
    path: '/games/minesweeper',
    difficulty: 'medium',
    sessionLength: '3-15 min',
    category: 'puzzle',
    multiplayer: ['best_score'],
  },
  {
    id: 'hangman',
    name: 'Hangman',
    description: 'Guess the word before time runs out',
    icon: 'PenLine',
    path: '/games/hangman',
    difficulty: 'easy',
    sessionLength: '2-5 min',
    category: 'word',
    multiplayer: ['first_to_win'],
  },
  {
    id: 'sudoku',
    name: 'Sudoku',
    description: 'Fill the 9x9 grid with logic',
    icon: 'Table2',
    path: '/games/sudoku',
    difficulty: 'medium',
    sessionLength: '5-20 min',
    category: 'puzzle',
    multiplayer: ['best_score'],
  },
  {
    id: 'wordle',
    name: 'Wordle',
    description: 'Guess the daily 5-letter word',
    icon: 'LetterText',
    path: '/games/wordle',
    difficulty: 'medium',
    sessionLength: '5-10 min',
    category: 'word',
    multiplayer: ['best_score'],
  },
  {
    id: 'crossword',
    name: 'Crossword',
    description: 'Daily themed crossword puzzle',
    icon: 'Grid2X2',
    path: '/games/crossword',
    difficulty: 'medium',
    sessionLength: '10-20 min',
    category: 'word',
    multiplayer: ['first_to_win'],
  },
  {
    id: 'snake',
    name: 'Snake',
    description: 'Eat, grow, survive',
    icon: 'Waypoints',
    path: '/games/snake',
    difficulty: 'easy',
    sessionLength: '2-10 min',
    category: 'arcade',
    multiplayer: ['best_score'],
  },
  {
    id: 'ultimate-tic-tac-toe',
    name: 'Ultimate Tic-Tac-Toe',
    description: 'Tic-tac-toe inception',
    icon: 'LayoutGrid',
    path: '/games/ultimate-tic-tac-toe',
    difficulty: 'hard',
    sessionLength: '10-20 min',
    category: 'strategy',
    multiplayer: ['vs', 'first_to_win'],
  },
  {
    id: 'mahjong',
    name: 'Mahjong Solitaire',
    description: 'Match tiles to clear the board',
    icon: 'Layers',
    path: '/games/mahjong',
    difficulty: 'hard',
    sessionLength: '10-20 min',
    category: 'puzzle',
    multiplayer: ['best_score'],
  },
  {
    id: 'nonogram',
    name: 'Nonogram',
    description: 'Solve clues to reveal pixel art',
    icon: 'Grip',
    path: '/games/nonogram',
    difficulty: 'medium',
    sessionLength: '10-20 min',
    category: 'puzzle',
    multiplayer: ['first_to_win'],
  },
  {
    id: 'checkers',
    name: 'Checkers',
    description: 'Classic board game vs AI',
    icon: 'Crown',
    path: '/games/checkers',
    difficulty: 'medium',
    sessionLength: '10-20 min',
    category: 'strategy',
    multiplayer: ['vs', 'first_to_win'],
  },
  {
    id: 'plinko',
    name: 'Plinko',
    description: 'Drop balls for multipliers',
    icon: 'Triangle',
    path: '/games/plinko',
    difficulty: 'easy',
    sessionLength: '2-5 min',
    category: 'arcade',
    multiplayer: ['best_score'],
  },
  {
    id: 'memory',
    name: 'Memory',
    description: 'Flip cards to find matching pairs',
    icon: 'FlipHorizontal',
    path: '/games/memory',
    difficulty: 'easy',
    sessionLength: '2-5 min',
    category: 'puzzle',
    multiplayer: ['first_to_win', 'best_score'],
  },
  {
    id: 'solitaire',
    name: 'Solitaire',
    description: 'Classic Klondike card game',
    icon: 'Spade',
    path: '/games/solitaire',
    difficulty: 'medium',
    sessionLength: '10-20 min',
    category: 'cards',
    subcategory: 'Solitaire',
    multiplayer: ['first_to_win'],
  },
  {
    id: 'backgammon',
    name: 'Backgammon',
    description: 'Classic dice board game vs AI',
    icon: 'Dices',
    path: '/games/backgammon',
    difficulty: 'hard',
    sessionLength: '15-30 min',
    category: 'strategy',
    multiplayer: ['vs', 'first_to_win'],
  },
  {
    id: 'chess',
    name: 'Chess',
    description: 'The ultimate strategy game vs AI',
    icon: 'ChessKnight',
    path: '/games/chess',
    difficulty: 'hard',
    sessionLength: '10-30 min',
    category: 'strategy',
    multiplayer: ['vs', 'first_to_win'],
  },
  // Phase 6: Card Games
  {
    id: 'blackjack',
    name: 'Blackjack',
    description: 'Beat the dealer to 21',
    icon: 'Clover',
    path: '/games/blackjack',
    difficulty: 'easy',
    sessionLength: '5-15 min',
    category: 'cards',
    subcategory: 'Casino',
    multiplayer: ['best_score'],
  },
  {
    id: 'video-poker',
    name: 'Video Poker',
    description: 'Jacks or Better draw poker',
    icon: 'Gem',
    path: '/games/video-poker',
    difficulty: 'medium',
    sessionLength: '5-15 min',
    category: 'cards',
    subcategory: 'Casino',
    multiplayer: ['best_score'],
  },
  {
    id: 'hearts',
    name: 'Hearts',
    description: 'Avoid hearts and the Queen of Spades',
    icon: 'Heart',
    path: '/games/hearts',
    difficulty: 'hard',
    sessionLength: '15-30 min',
    category: 'cards',
    subcategory: 'Trick-Taking',
    multiplayer: ['first_to_win'],
  },
  {
    id: 'spades',
    name: 'Spades',
    description: 'Partnership trick-taking with bids',
    icon: 'Swords',
    path: '/games/spades',
    difficulty: 'hard',
    sessionLength: '15-30 min',
    category: 'cards',
    subcategory: 'Trick-Taking',
    multiplayer: ['first_to_win'],
  },
  {
    id: 'crazy-eights',
    name: 'Crazy Eights',
    description: 'Match suit or rank, 8s are wild',
    icon: 'Infinity',
    path: '/games/crazy-eights',
    difficulty: 'easy',
    sessionLength: '5-10 min',
    category: 'cards',
    subcategory: 'Classic',
    multiplayer: ['first_to_win'],
  },
  {
    id: 'gin-rummy',
    name: 'Gin Rummy',
    description: 'Form melds and knock to win',
    icon: 'Wine',
    path: '/games/gin-rummy',
    difficulty: 'medium',
    sessionLength: '10-20 min',
    category: 'cards',
    subcategory: 'Rummy',
    multiplayer: ['first_to_win'],
  },
  {
    id: 'freecell',
    name: 'Freecell',
    description: 'Strategic solitaire — all cards visible',
    icon: 'LayoutDashboard',
    path: '/games/freecell',
    difficulty: 'medium',
    sessionLength: '10-20 min',
    category: 'cards',
    subcategory: 'Solitaire',
    multiplayer: ['first_to_win'],
  },
  // Phase 8: New Card Games
  {
    id: 'war',
    name: 'War',
    description: 'Flip cards — highest wins!',
    icon: 'Shield',
    path: '/games/war',
    difficulty: 'easy',
    sessionLength: '5-10 min',
    category: 'cards',
    subcategory: 'Classic',
    multiplayer: ['first_to_win'],
  },
  {
    id: 'go-fish',
    name: 'Go Fish',
    description: 'Ask for ranks, collect books of four',
    icon: 'Fish',
    path: '/games/go-fish',
    difficulty: 'easy',
    sessionLength: '5-10 min',
    category: 'cards',
    subcategory: 'Classic',
    multiplayer: ['first_to_win'],
  },
  {
    id: 'speed',
    name: 'Speed',
    description: 'Race to empty your hand first!',
    icon: 'Zap',
    path: '/games/speed',
    difficulty: 'medium',
    sessionLength: '3-5 min',
    category: 'cards',
    subcategory: 'Classic',
    multiplayer: ['first_to_win'],
  },
  {
    id: 'spoons',
    name: 'Spoons',
    description: 'Grab a spoon before they run out!',
    icon: 'Utensils',
    path: '/games/spoons',
    difficulty: 'medium',
    sessionLength: '10-15 min',
    category: 'cards',
    subcategory: 'Classic',
    multiplayer: ['first_to_win'],
  },
  {
    id: 'rummy-500',
    name: 'Rummy 500',
    description: 'Meld sets and runs to 500 points',
    icon: 'Banknote',
    path: '/games/rummy-500',
    difficulty: 'medium',
    sessionLength: '15-30 min',
    category: 'cards',
    subcategory: 'Rummy',
    multiplayer: ['first_to_win'],
  },
  {
    id: 'cribbage',
    name: 'Cribbage',
    description: 'Peg your way to 121 with 15s and runs',
    icon: 'BarChart3',
    path: '/games/cribbage',
    difficulty: 'hard',
    sessionLength: '15-30 min',
    category: 'cards',
    subcategory: 'Classic',
    multiplayer: ['first_to_win'],
  },
  {
    id: 'euchre',
    name: 'Euchre',
    description: 'Trick-taking with bowers and trump',
    icon: 'Handshake',
    path: '/games/euchre',
    difficulty: 'hard',
    sessionLength: '15-30 min',
    category: 'cards',
    subcategory: 'Trick-Taking',
    multiplayer: ['first_to_win'],
  },
  {
    id: 'texas-holdem',
    name: "Texas Hold'em",
    description: 'No-limit poker with community cards',
    icon: 'Star',
    path: '/games/texas-holdem',
    difficulty: 'hard',
    sessionLength: '15-30 min',
    category: 'cards',
    subcategory: 'Casino',
    multiplayer: ['vs', 'first_to_win'],
  },
  {
    id: 'bridge',
    name: 'Bridge',
    description: 'Bid, declare, and play with a partner',
    icon: 'Building2',
    path: '/games/bridge',
    difficulty: 'hard',
    sessionLength: '20-40 min',
    category: 'cards',
    subcategory: 'Trick-Taking',
    multiplayer: ['first_to_win'],
  },
  {
    id: 'canasta',
    name: 'Canasta',
    description: 'Build melds of seven with wild cards',
    icon: 'Boxes',
    path: '/games/canasta',
    difficulty: 'hard',
    sessionLength: '20-40 min',
    category: 'cards',
    subcategory: 'Rummy',
    multiplayer: ['first_to_win'],
  },
  // Phase 7: Arcade Games
  {
    id: 'centipede',
    name: 'Centipede',
    description: 'Shoot the centipede, dodge spiders',
    icon: 'Bug',
    path: '/games/centipede',
    difficulty: 'medium',
    sessionLength: '5-15 min',
    category: 'arcade',
    multiplayer: ['survival', 'best_score'],
  },
  {
    id: 'space-invaders',
    name: 'Space Invaders',
    description: 'Defend Earth from alien waves',
    icon: 'Rocket',
    path: '/games/space-invaders',
    difficulty: 'medium',
    sessionLength: '5-15 min',
    category: 'arcade',
    multiplayer: ['survival', 'best_score'],
  },
  {
    id: 'lode-runner',
    name: 'Lode Runner',
    description: 'Collect gold, dig traps, escape!',
    icon: 'Pickaxe',
    path: '/games/lode-runner',
    difficulty: 'hard',
    sessionLength: '15-30 min',
    category: 'arcade',
    multiplayer: ['best_score'],
  },
  {
    id: 'dino-runner',
    name: 'Dino Runner',
    description: 'Run, jump, and duck in this pixel-art endless runner!',
    icon: 'Footprints',
    path: '/games/dino-runner',
    difficulty: 'easy',
    sessionLength: '5-15 min',
    category: 'arcade',
    multiplayer: ['survival', 'best_score'],
  },
  {
    id: 'shalas',
    name: 'Shalas',
    description: 'Strategic card stacking on the table',
    icon: 'Peace',
    path: '/games/shalas',
    difficulty: 'medium',
    sessionLength: '10-20 min',
    category: 'cards',
    subcategory: 'Classic',
    multiplayer: ['vs'],
  },
]

/** Icon component map — maps icon string names to actual Lucide components */
/** Peace hand (V-sign / U+270C ✌) icon. */
function Peace({ className }: { className?: string }) {
  return createElement('svg', {
    xmlns: 'http://www.w3.org/2000/svg', viewBox: '0 0 24 24', className,
  },
    createElement('text', {
      x: '12', y: '18', textAnchor: 'middle', fontSize: '20',
      style: { userSelect: 'none' } as React.CSSProperties,
    }, '\u270C\uFE0F'),
  )
}

export const GAME_ICONS: Record<string, ComponentType<{ className?: string }>> = {
  Grid3X3,
  CircleDot,
  Hash,
  Bomb,
  PenLine,
  Table2,
  LetterText,
  Waypoints,
  LayoutGrid,
  Layers,
  Grip,
  Crown,
  Triangle,
  FlipHorizontal,
  Spade,
  Dices,
  ChessKnight,
  Clover,
  Gem,
  Heart,
  Swords,
  Infinity,
  Wine,
  LayoutDashboard,
  Bug,
  Rocket,
  Pickaxe,
  Footprints,
  Shield,
  Fish,
  Zap,
  Utensils,
  Banknote,
  BarChart3,
  Handshake,
  Star,
  Building2,
  Boxes,
  Grid2X2,
  Peace,
}

/** Category filter options for the hub page */
export const GAME_CATEGORIES = [
  { value: 'all', label: 'All' },
  { value: 'arcade', label: 'Arcade' },
  { value: 'cards', label: 'Cards' },
  { value: 'puzzle', label: 'Puzzle' },
  { value: 'strategy', label: 'Strategy' },
  { value: 'word', label: 'Word' },
] as const

/** Card game subcategory filter options */
export const CARD_SUBCATEGORIES = [
  { value: 'all', label: 'All Cards' },
  { value: 'Casino', label: 'Casino' },
  { value: 'Classic', label: 'Classic' },
  { value: 'Rummy', label: 'Rummy' },
  { value: 'Solitaire', label: 'Solitaire' },
  { value: 'Trick-Taking', label: 'Trick-Taking' },
] as const

/** Group-by options for the hub page */
export const GROUP_OPTIONS = [
  { value: 'none', label: 'Default' },
  { value: 'category', label: 'Category' },
  { value: 'difficulty', label: 'Difficulty' },
  { value: 'a-z', label: 'A – Z' },
  { value: 'recent', label: 'Recently Played' },
] as const

/** Display labels for game categories */
export const CATEGORY_LABELS: Record<string, string> = {
  arcade: 'Arcade',
  cards: 'Cards',
  puzzle: 'Puzzle',
  strategy: 'Strategy',
  word: 'Word',
}

/** Display labels for difficulty levels */
export const DIFFICULTY_LABELS: Record<string, string> = {
  easy: 'Easy',
  medium: 'Medium',
  hard: 'Hard',
}

/** Get the current user's ID from stored auth data (returns 0 if not logged in). */
function getStoredUserId(): number {
  try {
    const raw = localStorage.getItem('auth_user')
    if (raw) {
      const user = JSON.parse(raw)
      return user.id || 0
    }
  } catch { /* ignore */ }
  return 0
}

/** localStorage key prefix for all game data — scoped to the current user. */
export function getStoragePrefix(): string {
  return `zenith-games-u${getStoredUserId()}-`
}

/**
 * @deprecated Use getStoragePrefix() for user-scoped keys.
 * Kept as fallback for static import contexts.
 */
export const STORAGE_PREFIX = 'zenith-games-'
